// AUTO-GENERATED by build-challenges.mjs — do not edit by hand.
// Source of truth: challenges/world*.json + concepts.json. Rebuild with: node build-challenges.mjs
window.CHALLENGES = {
  "world1": [
    {
      "id": "w1c01",
      "world": 1,
      "worldName": "XPath Navigator",
      "title": "Personen im Brief",
      "task": "Selektiere alle tei:persName-Elemente in diesem Brief und gib ihren Textinhalt aus.",
      "type": "xpath",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Carl Maria von Weber",
        "Caroline Brandt",
        "Lina",
        "Friedrich Kind",
        "Brühl",
        "Carl"
      ],
      "hints": [
        "TEI-Elemente stehen im Namespace tei:. Der Präfix muss immer mit angegeben werden.",
        "Der // Operator sucht rekursiv durch den ganzen Baum — du musst nicht den vollen Pfad kennen.",
        "string() oder text() gibt den Textinhalt zurück: //tei:persName/string()"
      ],
      "solution": "//tei:persName/string()",
      "explanation": "// ist die Kurzschreibweise für /descendant-or-self::node()/. In der WeGA werden Personenreferenzen immer über tei:persName mit @key kodiert — dieses Pattern findest du überall in den Brief-Stylesheets.",
      "conceptTag": "Grundnavigation"
    },
    {
      "id": "w1c02",
      "world": 1,
      "worldName": "XPath Navigator",
      "title": "Datum des Briefes",
      "task": "Gib das @when-Attribut des Versanddatums aus (correspAction[@type='sent']).",
      "type": "xpath",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "1817-02-12"
      ],
      "hints": [
        "Versandaktionen stehen in tei:correspAction[@type='sent'].",
        "Attribute selektierst du mit @: tei:date/@when.",
        "//tei:correspAction[@type='sent']/tei:date/@when"
      ],
      "solution": "//tei:correspAction[@type='sent']/tei:date/@when",
      "explanation": "@when liefert das normierte ISO-Datum. correspDesc/correspAction ist das zentrale WeGA-Pattern für Korrespondenz-Metadaten — sent und received unterscheiden Absender und Empfänger.",
      "conceptTag": "Grundnavigation"
    },
    {
      "id": "w1c03",
      "world": 1,
      "worldName": "XPath Navigator",
      "title": "Absender",
      "task": "Gib den Namen des Absenders aus (persName innerhalb der sent-Aktion).",
      "type": "xpath",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Carl Maria von Weber"
      ],
      "hints": [
        "Der Absender steckt in correspAction[@type='sent'].",
        "Du kannst // auch mitten im Pfad verwenden, um beliebig tief zu suchen.",
        "//tei:correspAction[@type='sent']//tei:persName/string()"
      ],
      "solution": "//tei:correspAction[@type='sent']//tei:persName/string()",
      "explanation": "Das // mitten im Ausdruck bedeutet 'irgendwo darunter'. So musst du die genaue Schachtelung nicht kennen.",
      "conceptTag": "Grundnavigation"
    },
    {
      "id": "w1c04",
      "world": 1,
      "worldName": "XPath Navigator",
      "title": "Alle @key-Attribute",
      "task": "Selektiere alle @key-Attribute aller tei:persName-Elemente.",
      "type": "xpath",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "A002068",
        "A002078",
        "A002078",
        "A002099",
        "A002101",
        "A002068"
      ],
      "hints": [
        "@key ist ein Attribut auf tei:persName.",
        "Attribute werden auch als Knoten ausgewählt: //tei:persName/@key.",
        "//tei:persName/@key"
      ],
      "solution": "//tei:persName/@key",
      "explanation": "@key referenziert den eindeutigen WeGA-Datensatz einer Person (Pattern A00xxxx). Dieselbe Person kann mehrfach vorkommen — daher tauchen Keys mehrfach auf.",
      "conceptTag": "Grundnavigation"
    },
    {
      "id": "w1c05",
      "world": 1,
      "worldName": "XPath Navigator",
      "title": "Kommentar-Notizen",
      "task": "Selektiere alle tei:note mit @type='commentary' und gib ihren Text aus.",
      "type": "xpath",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Weber arbeitete von 1815 bis 1819 an mehreren Klavierwerken parallel."
      ],
      "hints": [
        "Ein Predicate [ ] filtert nach einer Bedingung.",
        "Vergleiche das Attribut: [@type='commentary'].",
        "//tei:note[@type='commentary']/string()"
      ],
      "solution": "//tei:note[@type='commentary']/string()",
      "explanation": "In der WeGA unterscheidet @type auf tei:note redaktionelle Ebenen: commentary (Sachkommentar) vs. textConst (Textkonstitution). Predicates [ ] filtern Knoten nach Bedingungen.",
      "conceptTag": "Predicates"
    },
    {
      "id": "w1c06",
      "world": 1,
      "worldName": "XPath Navigator",
      "title": "Erster Absatz",
      "task": "Gib den Text des ersten tei:p im body aus.",
      "type": "xpath",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Meine innig geliebte Lina! Schon wieder sind einige Tage vergangen, ohne dass ich Dir schreiben konnte. Die Proben zur Freischütz-Ouvertüre nehmen all meine Zeit in Anspruch."
      ],
      "hints": [
        "Mit [1] greifst du das erste Element einer Sequenz.",
        "Achtung: //tei:p[1] heißt 'jedes p, das erstes Kind ist'. Du willst das erste aller p.",
        "Klammere die Sequenz zuerst: (//tei:body//tei:p)[1]/string()"
      ],
      "solution": "(//tei:body//tei:p)[1]/string()",
      "explanation": "Der Unterschied zwischen //tei:p[1] und (//tei:p)[1] ist eine klassische Stolperfalle: Ersteres filtert pro Eltern-Kontext, Letzteres nummeriert die gesamte Ergebnismenge.",
      "conceptTag": "Predicates"
    },
    {
      "id": "w1c07",
      "world": 1,
      "worldName": "XPath Navigator",
      "title": "Werkverweise",
      "task": "Selektiere alle tei:rs[@type='work'] und gib ihren Text aus.",
      "type": "xpath",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Freischütz",
        "Aufforderung zum Tanz"
      ],
      "hints": [
        "tei:rs ist eine referenzierende Zeichenkette (referencing string).",
        "Filtere nach @type='work'.",
        "//tei:rs[@type='work']/string()"
      ],
      "solution": "//tei:rs[@type='work']/string()",
      "explanation": "tei:rs[@type='work'] markiert Werkverweise im Fließtext. In der WeGA verlinken diese über @key auf Werk-Datensätze.",
      "conceptTag": "Predicates"
    },
    {
      "id": "w1c08",
      "world": 1,
      "worldName": "XPath Navigator",
      "title": "Nur Personen mit Key",
      "task": "Selektiere nur die tei:persName, die ein @key-Attribut besitzen, und gib ihren Text aus.",
      "type": "xpath",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Carl Maria von Weber",
        "Caroline Brandt",
        "Lina",
        "Friedrich Kind",
        "Brühl",
        "Carl"
      ],
      "hints": [
        "Ein Predicate kann auch nur die Existenz eines Attributs prüfen.",
        "[@key] ohne Vergleich ist wahr, wenn das Attribut vorhanden ist.",
        "//tei:persName[@key]/string()"
      ],
      "solution": "//tei:persName[@key]/string()",
      "explanation": "Ein nacktes [@key] testet auf Existenz. In echten WeGA-Daten gibt es auch persName ohne @key (nicht identifizierte Personen) — dieses Pattern filtert die identifizierten heraus.",
      "conceptTag": "Predicates"
    },
    {
      "id": "w1c09",
      "world": 1,
      "worldName": "XPath Navigator",
      "title": "Folgegeschwister des Datums",
      "task": "Gib die local-name() aller Folgegeschwister-Elemente von tei:date aus.",
      "type": "xpath",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "placeName"
      ],
      "hints": [
        "Die Achse following-sibling:: liefert alle nachfolgenden Geschwister.",
        "local-name() gibt den Elementnamen ohne Namespace-Präfix.",
        "//tei:date/following-sibling::*/local-name()"
      ],
      "solution": "//tei:date/following-sibling::*/local-name()",
      "explanation": "Achsen (axes) wie following-sibling::, preceding::, ancestor:: navigieren relativ zum Kontextknoten. local-name() ist nützlich, wenn man Namespace-Präfixe ignorieren will.",
      "conceptTag": "Achsen und Funktionen"
    },
    {
      "id": "w1c10",
      "world": 1,
      "worldName": "XPath Navigator",
      "title": "Anzahl der Personen",
      "task": "Zähle alle tei:persName-Elemente im Dokument.",
      "type": "xpath",
      "fixture": "letter_001",
      "expectedType": "number",
      "expected": 6,
      "hints": [
        "count() nimmt eine Sequenz und gibt deren Länge zurück.",
        "count( hier die Sequenz )",
        "count(//tei:persName)"
      ],
      "solution": "count(//tei:persName)",
      "explanation": "count() ist eine Aggregatfunktion. Sie zählt Knoten, nicht Zeichen — perfekt für 'Wie oft kommt X vor?'.",
      "conceptTag": "Achsen und Funktionen"
    },
    {
      "id": "w1c11",
      "world": 1,
      "worldName": "XPath Navigator",
      "title": "Normalisierter Text",
      "task": "Gib den normalisierten Text des ersten tei:persName aus (überflüssige Leerzeichen entfernt).",
      "type": "xpath",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Carl Maria von Weber"
      ],
      "hints": [
        "normalize-space() entfernt führende/folgende Leerzeichen und kollabiert mehrfache.",
        "Achtung: normalize-space() erwartet genau einen Wert. //tei:persName[1] kann mehrere liefern!",
        "Klammere zuerst: normalize-space((//tei:persName)[1])"
      ],
      "solution": "normalize-space((//tei:persName)[1])",
      "explanation": "normalize-space() akzeptiert nur einen einzelnen String. Deshalb muss (//tei:persName)[1] erst die Sequenz auf genau einen Knoten reduzieren, sonst gibt es einen XPTY0004-Fehler.",
      "conceptTag": "Achsen und Funktionen"
    },
    {
      "id": "w1c12",
      "world": 1,
      "worldName": "XPath Navigator",
      "title": "Distinkte note-Typen",
      "task": "Gib alle unterschiedlichen @type-Werte der tei:note-Elemente aus.",
      "type": "xpath",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "commentary",
        "textConst"
      ],
      "hints": [
        "distinct-values() entfernt Duplikate aus einer Sequenz.",
        "Sammle erst alle @type, dann distinct.",
        "distinct-values(//tei:note/@type)"
      ],
      "solution": "distinct-values(//tei:note/@type)",
      "explanation": "distinct-values() ist eine XPath-2.0/3.1-Funktion (im Browser-XSLT 1.0 nicht verfügbar!). FontoxPath unterstützt sie. Sehr nützlich, um z. B. alle vorkommenden Typ-Werte zu inventarisieren.",
      "conceptTag": "Achsen und Funktionen"
    }
  ],
  "world2": [
    {
      "id": "w2c01",
      "world": 2,
      "worldName": "FLWOR Forge",
      "title": "Alle Briefdaten",
      "task": "Iteriere mit for über alle tei:date mit @when und gib jeweils das Datum als String zurück.",
      "type": "flwor",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "1817-02-12"
      ],
      "hints": [
        "FLWOR steht für for-let-where-order by-return.",
        "for $d in ... bindet jede gefundene date an $d.",
        "for $d in //tei:date[@when] return string($d/@when)"
      ],
      "solution": "for $d in //tei:date[@when] return string($d/@when)",
      "explanation": "for bindet jeden Knoten der Sequenz nacheinander an die Variable und wertet den return-Ausdruck für jeden aus. Das ist die Grundschleife von XQuery.",
      "conceptTag": "for/return"
    },
    {
      "id": "w2c02",
      "world": 2,
      "worldName": "FLWOR Forge",
      "title": "Name und Key als Paar",
      "task": "Gib für jede tei:persName mit @key einen String 'Name [Key]' zurück.",
      "type": "flwor",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Carl Maria von Weber [A002068]",
        "Caroline Brandt [A002078]",
        "Lina [A002078]",
        "Friedrich Kind [A002099]",
        "Brühl [A002101]",
        "Carl [A002068]"
      ],
      "hints": [
        "concat() fügt mehrere Strings zusammen.",
        "Innerhalb von for kannst du auf $p und $p/@key zugreifen.",
        "for $p in //tei:persName[@key] return concat(string($p), ' [', $p/@key, ']')"
      ],
      "solution": "for $p in //tei:persName[@key] return concat(string($p), ' [', $p/@key, ']')",
      "explanation": "concat() ist in XPath/XQuery die Standard-Funktion zum Zusammenbauen von Strings. So formatiert man Ausgaben für Register oder Listen.",
      "conceptTag": "for/return"
    },
    {
      "id": "w2c03",
      "world": 2,
      "worldName": "FLWOR Forge",
      "title": "Werktitel",
      "task": "Gib mit for alle Werktitel (tei:rs[@type='work']) als String zurück.",
      "type": "flwor",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Freischütz",
        "Aufforderung zum Tanz"
      ],
      "hints": [
        "Filtere wie in XPath mit einem Predicate.",
        "string($r) konvertiert den Knoten in seinen Textinhalt.",
        "for $r in //tei:rs[@type='work'] return string($r)"
      ],
      "solution": "for $r in //tei:rs[@type='work'] return string($r)",
      "explanation": "for-Schleifen können dieselben Predicates verwenden wie reine XPath-Ausdrücke. FLWOR fügt darüber hinaus let, where und order by hinzu.",
      "conceptTag": "for/return"
    },
    {
      "id": "w2c04",
      "world": 2,
      "worldName": "FLWOR Forge",
      "title": "let für den Absender",
      "task": "Binde mit let den ersten Absender-persName an eine Variable und gib seinen Namen zurück.",
      "type": "flwor",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Carl Maria von Weber"
      ],
      "hints": [
        "let $x := ... bindet einen Wert genau einmal (keine Iteration).",
        "Nutze [1], um den ersten Treffer zu nehmen.",
        "let $s := //tei:correspAction[@type='sent']//tei:persName[1] return string($s)"
      ],
      "solution": "let $s := //tei:correspAction[@type='sent']//tei:persName[1] return string($s)",
      "explanation": "Anders als for iteriert let nicht — es bindet einen einzigen Wert (auch eine ganze Sequenz). Ideal für Zwischenergebnisse.",
      "conceptTag": "let"
    },
    {
      "id": "w2c05",
      "world": 2,
      "worldName": "FLWOR Forge",
      "title": "where als Filter",
      "task": "Iteriere über alle tei:note und gib mit where nur die commentary-Notizen zurück.",
      "type": "flwor",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Weber arbeitete von 1815 bis 1819 an mehreren Klavierwerken parallel."
      ],
      "hints": [
        "where filtert die iterierten Elemente nach einer Bedingung.",
        "Vergleiche $n/@type = 'commentary'.",
        "for $n in //tei:note where $n/@type = 'commentary' return string($n)"
      ],
      "solution": "for $n in //tei:note where $n/@type = 'commentary' return string($n)",
      "explanation": "where ist das FLWOR-Pendant zum Predicate. Bei komplexen Bedingungen ist where oft lesbarer als ein langes [ ].",
      "conceptTag": "where"
    },
    {
      "id": "w2c06",
      "world": 2,
      "worldName": "FLWOR Forge",
      "title": "for + let + where kombiniert",
      "task": "Zähle für jeden Absatz (tei:p im body) die Wörter und gib 'id: anzahl' nur für Absätze mit mehr als 10 Wörtern zurück.",
      "type": "flwor",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "p1: 26",
        "p2: 20",
        "p3: 19",
        "p4: 14"
      ],
      "hints": [
        "tokenize(string, ' ') zerlegt einen String an Leerzeichen in eine Sequenz.",
        "Kombiniere for $p ... let $wc := ... where $wc > 10.",
        "for $p in //tei:body//tei:p let $wc := count(tokenize(normalize-space($p), ' ')) where $wc > 10 return concat($p/@xml:id, ': ', $wc)"
      ],
      "solution": "for $p in //tei:body//tei:p let $wc := count(tokenize(normalize-space($p), ' ')) where $wc > 10 return concat($p/@xml:id, ': ', $wc)",
      "explanation": "Hier greifen alle FLWOR-Klauseln ineinander: for iteriert, let berechnet pro Iteration die Wortzahl, where filtert, return formatiert. tokenize + count ist das Standardmuster zum Wörterzählen.",
      "conceptTag": "for/let/where"
    },
    {
      "id": "w2c07",
      "world": 2,
      "worldName": "FLWOR Forge",
      "title": "Verschachteltes for",
      "task": "Gib für jeden Brief in der Sammlung ein Paar 'Absender -> Empfänger' zurück (letters_collection).",
      "type": "flwor",
      "fixture": "letters_collection",
      "expectedType": "stringArray",
      "expected": [
        "Carl Maria von Weber -> Caroline Brandt",
        "Caroline Brandt -> Carl Maria von Weber",
        "Friedrich Kind -> Carl Maria von Weber",
        "Carl Maria von Weber -> Karl von Brühl",
        "Caroline Brandt -> Friedrich Kind"
      ],
      "hints": [
        "Du kannst mehrere for-Klauseln verschachteln oder innerhalb des return weiter navigieren.",
        "Hole Absender und Empfänger aus correspAction[@type='sent'] bzw. 'received'.",
        "for $l in //tei:letter for $s in $l/tei:correspAction[@type='sent']/tei:persName return concat(string($s), ' -> ', string($l/tei:correspAction[@type='received']/tei:persName))"
      ],
      "solution": "for $l in //tei:letter for $s in $l/tei:correspAction[@type='sent']/tei:persName return concat(string($s), ' -> ', string($l/tei:correspAction[@type='received']/tei:persName))",
      "explanation": "Mehrere for-Klauseln erzeugen ein kartesisches Produkt — hier aber kontrolliert, weil das innere for auf $l relativ navigiert. So verknüpft man Daten innerhalb eines Dokuments.",
      "conceptTag": "verschachteltes for"
    },
    {
      "id": "w2c08",
      "world": 2,
      "worldName": "FLWOR Forge",
      "title": "order by Datum",
      "task": "Gib die Versanddaten aller Briefe in der Sammlung aufsteigend sortiert zurück (letters_collection).",
      "type": "flwor",
      "fixture": "letters_collection",
      "expectedType": "stringArray",
      "expected": [
        "1817-02-28",
        "1817-03-01",
        "1817-03-05",
        "1817-04-10",
        "1817-04-15"
      ],
      "hints": [
        "order by ... ascending sortiert die Iteration.",
        "Sortiere nach dem @when des sent-Datums.",
        "for $l in //tei:letter order by $l/tei:correspAction[@type='sent']/tei:date/@when ascending return string($l/tei:correspAction[@type='sent']/tei:date/@when)"
      ],
      "solution": "for $l in //tei:letter order by $l/tei:correspAction[@type='sent']/tei:date/@when ascending return string($l/tei:correspAction[@type='sent']/tei:date/@when)",
      "explanation": "order by sortiert die for-Iteration vor dem return. Da @when ein ISO-Datum ist, ergibt die String-Sortierung automatisch chronologische Reihenfolge.",
      "conceptTag": "order by"
    },
    {
      "id": "w2c09",
      "world": 2,
      "worldName": "FLWOR Forge",
      "title": "Distinkte note-Typen",
      "task": "Gib alle unterschiedlichen @type-Werte der tei:note zurück.",
      "type": "flwor",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "commentary",
        "textConst"
      ],
      "hints": [
        "distinct-values() entfernt Duplikate.",
        "Hier brauchst du kein for — die Funktion reicht.",
        "distinct-values(//tei:note/@type)"
      ],
      "solution": "distinct-values(//tei:note/@type)",
      "explanation": "Auch ein einzelner Funktionsaufruf ist ein gültiger XQuery-Ausdruck. distinct-values() inventarisiert vorkommende Werte — ein häufiges erstes Erkundungs-Query.",
      "conceptTag": "Aggregation"
    },
    {
      "id": "w2c10",
      "world": 2,
      "worldName": "FLWOR Forge",
      "title": "count + concat",
      "task": "Binde alle tei:persName an eine Variable und gib 'Anzahl: N' zurück.",
      "type": "flwor",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Anzahl: 6"
      ],
      "hints": [
        "let bindet die ganze Sequenz an eine Variable.",
        "count($ps) zählt, concat() baut den String.",
        "let $ps := //tei:persName return concat('Anzahl: ', count($ps))"
      ],
      "solution": "let $ps := //tei:persName return concat('Anzahl: ', count($ps))",
      "explanation": "let bindet hier eine ganze Knotensequenz. count() macht daraus eine Zahl, concat() formatiert die Ausgabe. concat akzeptiert automatisch auch Zahlen.",
      "conceptTag": "Aggregation"
    },
    {
      "id": "w2c11",
      "world": 2,
      "worldName": "FLWOR Forge",
      "title": "ID und Absender aus der Sammlung",
      "task": "Gib für jeden Brief 'xml:id: Absender' zurück (letters_collection).",
      "type": "flwor",
      "fixture": "letters_collection",
      "expectedType": "stringArray",
      "expected": [
        "A040010: Carl Maria von Weber",
        "A040011: Caroline Brandt",
        "A040012: Friedrich Kind",
        "A040013: Carl Maria von Weber",
        "A040014: Caroline Brandt"
      ],
      "hints": [
        "Greife auf $l/@xml:id und den sent-persName zu.",
        "concat() verbindet beide.",
        "for $l in //tei:letter return concat(string($l/@xml:id), ': ', string($l/tei:correspAction[@type='sent']/tei:persName))"
      ],
      "solution": "for $l in //tei:letter return concat(string($l/@xml:id), ': ', string($l/tei:correspAction[@type='sent']/tei:persName))",
      "explanation": "@xml:id ist die eindeutige Dokument-Kennung im WeGA-Pattern A04xxxx. So baut man kompakte Register-Einträge über eine Briefsammlung.",
      "conceptTag": "for/return"
    },
    {
      "id": "w2c12",
      "world": 2,
      "worldName": "FLWOR Forge",
      "title": "Unique Personen, sortiert",
      "task": "Gib alle eindeutigen Personennamen alphabetisch sortiert zurück.",
      "type": "flwor",
      "fixture": "letter_001",
      "expectedType": "stringArray",
      "expected": [
        "Brühl",
        "Carl",
        "Carl Maria von Weber",
        "Caroline Brandt",
        "Friedrich Kind",
        "Lina"
      ],
      "hints": [
        "Erst distinct-values, dann in einem for sortieren.",
        "let $all := distinct-values(...) for $p in $all order by $p return $p",
        "let $all := distinct-values(//tei:persName/string()) for $p in $all order by $p return $p"
      ],
      "solution": "let $all := distinct-values(//tei:persName/string()) for $p in $all order by $p return $p",
      "explanation": "Erst dedupliziert distinct-values, dann sortiert order by die verbleibende Sequenz. Das Zusammenspiel von let (einmal binden) und for (iterieren + sortieren) ist das Standardmuster für sortierte Register.",
      "conceptTag": "order by"
    }
  ],
  "world3": [
    {
      "id": "w3c01",
      "world": 3,
      "worldName": "XSLT Basics",
      "title": "Absender ausgeben",
      "task": "Gib den Namen des Absenders in einem <p>-Element aus.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<p>Carl Maria von Weber</p>",
      "hints": [
        "xsl:value-of select=\"...\" gibt den Stringwert eines Knotens aus.",
        "Der Absender steckt in tei:correspAction[@type='sent']//tei:persName.",
        "<p><xsl:value-of select=\"//tei:correspAction[@type='sent']//tei:persName\"/></p>"
      ],
      "solution": "<p><xsl:value-of select=\"//tei:correspAction[@type='sent']//tei:persName\"/></p>",
      "explanation": "xsl:value-of ist die Brot-und-Butter-Anweisung in XSLT: sie nimmt den Stringwert eines XPath-Ausdrucks und schreibt ihn in die Ausgabe.",
      "conceptTag": "value-of"
    },
    {
      "id": "w3c02",
      "world": 3,
      "worldName": "XSLT Basics",
      "title": "Datum mit Attribut",
      "task": "Gib das Datum als <time datetime=\"ISO\">Anzeigetext</time> aus. Das @when als datetime-Attribut, der Elementtext als Anzeige.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<time datetime=\"1817-02-12\">12. Februar 1817</time>",
      "hints": [
        "Mit geschweiften Klammern {…} setzt du XPath-Werte in Attribute (Attribute Value Template).",
        "datetime=\"{...}\" wertet den XPath darin aus.",
        "<time datetime=\"{//tei:correspAction[@type='sent']/tei:date/@when}\"><xsl:value-of select=\"//tei:correspAction[@type='sent']/tei:date\"/></time>"
      ],
      "solution": "<time datetime=\"{//tei:correspAction[@type='sent']/tei:date/@when}\"><xsl:value-of select=\"//tei:correspAction[@type='sent']/tei:date\"/></time>",
      "explanation": "Attribute Value Templates ({…}) sind die kompakte Art, dynamische Attributwerte zu erzeugen. Alternativ geht xsl:attribute (siehe spätere Challenge).",
      "conceptTag": "Attribute Value Template"
    },
    {
      "id": "w3c03",
      "world": 3,
      "worldName": "XSLT Basics",
      "title": "Von/An als Definitionsliste",
      "task": "Erzeuge eine <dl> mit <dt>Von:</dt><dd>Absender</dd><dt>An:</dt><dd>Empfänger</dd>.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<dl><dt>Von:</dt><dd>Carl Maria von Weber</dd><dt>An:</dt><dd>Caroline Brandt</dd></dl>",
      "hints": [
        "dt = Term, dd = Beschreibung.",
        "Empfänger steht in correspAction[@type='received'].",
        "<dl><dt>Von:</dt><dd><xsl:value-of select=\"//tei:correspAction[@type='sent']//tei:persName\"/></dd><dt>An:</dt><dd><xsl:value-of select=\"//tei:correspAction[@type='received']//tei:persName\"/></dd></dl>"
      ],
      "solution": "<dl><dt>Von:</dt><dd><xsl:value-of select=\"//tei:correspAction[@type='sent']//tei:persName\"/></dd><dt>An:</dt><dd><xsl:value-of select=\"//tei:correspAction[@type='received']//tei:persName\"/></dd></dl>",
      "explanation": "Statischer HTML-Text und xsl:value-of lassen sich frei mischen. So baut man strukturiertes Markup um dynamische Werte herum.",
      "conceptTag": "value-of"
    },
    {
      "id": "w3c04",
      "world": 3,
      "worldName": "XSLT Basics",
      "title": "Alle Personen als Liste",
      "task": "Erzeuge eine <ul> mit einem <li> pro tei:persName, via xsl:for-each.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<ul><li>Carl Maria von Weber</li><li>Caroline Brandt</li><li>Lina</li><li>Friedrich Kind</li><li>Brühl</li><li>Carl</li></ul>",
      "hints": [
        "xsl:for-each iteriert über eine Knotenmenge.",
        "Innerhalb gibt . den aktuellen Knoten an.",
        "<ul><xsl:for-each select=\"//tei:persName\"><li><xsl:value-of select=\".\"/></li></xsl:for-each></ul>"
      ],
      "solution": "<ul><xsl:for-each select=\"//tei:persName\"><li><xsl:value-of select=\".\"/></li></xsl:for-each></ul>",
      "explanation": "xsl:for-each ist die explizite Schleife (pull-style). In World 4 lernst du die WeGA-bevorzugte Alternative kennen: apply-templates (push-style).",
      "conceptTag": "for-each"
    },
    {
      "id": "w3c05",
      "world": 3,
      "worldName": "XSLT Basics",
      "title": "Tabelle aus der Sammlung",
      "task": "Erzeuge eine <table> mit einer Zeile pro Brief (Absender + Datum) aus letters_collection.",
      "type": "xslt",
      "fixture": "letters_collection",
      "expectedType": "html",
      "expected": "<table><tr><td>Carl Maria von Weber</td><td>1817-03-01</td></tr><tr><td>Caroline Brandt</td><td>1817-03-05</td></tr><tr><td>Friedrich Kind</td><td>1817-02-28</td></tr><tr><td>Carl Maria von Weber</td><td>1817-04-10</td></tr><tr><td>Caroline Brandt</td><td>1817-04-15</td></tr></table>",
      "hints": [
        "Iteriere über //tei:letter.",
        "Innerhalb navigierst du relativ: tei:correspAction[@type='sent']/tei:persName.",
        "<table><xsl:for-each select=\"//tei:letter\"><tr><td><xsl:value-of select=\"tei:correspAction[@type='sent']/tei:persName\"/></td><td><xsl:value-of select=\"tei:correspAction[@type='sent']/tei:date/@when\"/></td></tr></xsl:for-each></table>"
      ],
      "solution": "<table><xsl:for-each select=\"//tei:letter\"><tr><td><xsl:value-of select=\"tei:correspAction[@type='sent']/tei:persName\"/></td><td><xsl:value-of select=\"tei:correspAction[@type='sent']/tei:date/@when\"/></td></tr></xsl:for-each></table>",
      "explanation": "Innerhalb von xsl:for-each ist der Kontextknoten der jeweilige Brief — daher navigiert man relativ (ohne führendes //). Der Browser ergänzt beim table-Output automatisch ein tbody.",
      "conceptTag": "for-each"
    },
    {
      "id": "w3c06",
      "world": 3,
      "worldName": "XSLT Basics",
      "title": "Sortierte Liste",
      "task": "Erzeuge eine <ul> aller tei:persName, alphabetisch sortiert (xsl:sort).",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<ul><li>Brühl</li><li>Carl</li><li>Carl Maria von Weber</li><li>Caroline Brandt</li><li>Friedrich Kind</li><li>Lina</li></ul>",
      "hints": [
        "xsl:sort steht als erstes Kind innerhalb von xsl:for-each.",
        "<xsl:sort select=\".\"/> sortiert nach dem Knotentext.",
        "<ul><xsl:for-each select=\"//tei:persName\"><xsl:sort select=\".\"/><li><xsl:value-of select=\".\"/></li></xsl:for-each></ul>"
      ],
      "solution": "<ul><xsl:for-each select=\"//tei:persName\"><xsl:sort select=\".\"/><li><xsl:value-of select=\".\"/></li></xsl:for-each></ul>",
      "explanation": "xsl:sort muss direkt nach dem öffnenden for-each (oder apply-templates) stehen, vor dem Schleifenkörper. Standard ist aufsteigend alphabetisch.",
      "conceptTag": "sort"
    },
    {
      "id": "w3c07",
      "world": 3,
      "worldName": "XSLT Basics",
      "title": "xsl:if — nur Kommentare",
      "task": "Iteriere über alle tei:note und gib nur die commentary-Notizen in einem <p> aus (xsl:if).",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<div><p>Weber arbeitete von 1815 bis 1819 an mehreren Klavierwerken parallel.</p></div>",
      "hints": [
        "xsl:if test=\"...\" gibt seinen Inhalt nur aus, wenn die Bedingung wahr ist.",
        "XSLT 1.0 hat kein else — dafür gibt es xsl:choose.",
        "<div><xsl:for-each select=\"//tei:note\"><xsl:if test=\"@type='commentary'\"><p><xsl:value-of select=\".\"/></p></xsl:if></xsl:for-each></div>"
      ],
      "solution": "<div><xsl:for-each select=\"//tei:note\"><xsl:if test=\"@type='commentary'\"><p><xsl:value-of select=\".\"/></p></xsl:if></xsl:for-each></div>",
      "explanation": "xsl:if kennt kein else (das gibt es erst mit xsl:choose). Für reine 'nur wenn'-Logik ist xsl:if die einfachste Wahl.",
      "conceptTag": "if"
    },
    {
      "id": "w3c08",
      "world": 3,
      "worldName": "XSLT Basics",
      "title": "xsl:choose — Klassen nach Typ",
      "task": "Gib für jede tei:note ein <span> mit class='comment' (bei commentary) oder 'other' (sonst) und dem @type als Text aus.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<div><span class=\"comment\">commentary</span><span class=\"other\">textConst</span></div>",
      "hints": [
        "xsl:choose mit xsl:when und xsl:otherwise ist das if/else if/else von XSLT.",
        "Setze die Klasse über xsl:attribute oder ein AVT.",
        "<div><xsl:for-each select=\"//tei:note\"><span><xsl:attribute name=\"class\"><xsl:choose><xsl:when test=\"@type='commentary'\">comment</xsl:when><xsl:otherwise>other</xsl:otherwise></xsl:choose></xsl:attribute><xsl:value-of select=\"@type\"/></span></xsl:for-each></div>"
      ],
      "solution": "<div><xsl:for-each select=\"//tei:note\"><span><xsl:attribute name=\"class\"><xsl:choose><xsl:when test=\"@type='commentary'\">comment</xsl:when><xsl:otherwise>other</xsl:otherwise></xsl:choose></xsl:attribute><xsl:value-of select=\"@type\"/></span></xsl:for-each></div>",
      "explanation": "xsl:choose/when/otherwise deckt mehrstufige Fallunterscheidungen ab. Hier steuert es den Wert eines Attributs, das mit xsl:attribute gesetzt wird.",
      "conceptTag": "choose"
    },
    {
      "id": "w3c09",
      "world": 3,
      "worldName": "XSLT Basics",
      "title": "Bedingtes Attribut",
      "task": "Erzeuge eine <ul> aller tei:persName. Wenn @key existiert, setze ein data-key-Attribut mit dessen Wert.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<ul><li data-key=\"A002068\">Carl Maria von Weber</li><li data-key=\"A002078\">Caroline Brandt</li><li data-key=\"A002078\">Lina</li><li data-key=\"A002099\">Friedrich Kind</li><li data-key=\"A002101\">Brühl</li><li data-key=\"A002068\">Carl</li></ul>",
      "hints": [
        "xsl:attribute innerhalb eines xsl:if setzt das Attribut nur bedingt.",
        "xsl:attribute muss vor jeglichem Textinhalt des li stehen.",
        "<ul><xsl:for-each select=\"//tei:persName\"><li><xsl:if test=\"@key\"><xsl:attribute name=\"data-key\"><xsl:value-of select=\"@key\"/></xsl:attribute></xsl:if><xsl:value-of select=\".\"/></li></xsl:for-each></ul>"
      ],
      "solution": "<ul><xsl:for-each select=\"//tei:persName\"><li><xsl:if test=\"@key\"><xsl:attribute name=\"data-key\"><xsl:value-of select=\"@key\"/></xsl:attribute></xsl:if><xsl:value-of select=\".\"/></li></xsl:for-each></ul>",
      "explanation": "Wichtig: xsl:attribute muss VOR jeglichem Kindinhalt stehen, sonst ignoriert der Prozessor es (Attribute kommen vor Text). xsl:if macht das Attribut optional.",
      "conceptTag": "attribute"
    },
    {
      "id": "w3c10",
      "world": 3,
      "worldName": "XSLT Basics",
      "title": "Link aus @key erzeugen",
      "task": "Erzeuge für jede tei:persName[@key] einen Link <a href=\"/person/KEY\">Name</a> in einer <ul>.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<ul><li><a href=\"/person/A002068\">Carl Maria von Weber</a></li><li><a href=\"/person/A002078\">Caroline Brandt</a></li><li><a href=\"/person/A002078\">Lina</a></li><li><a href=\"/person/A002099\">Friedrich Kind</a></li><li><a href=\"/person/A002101\">Brühl</a></li><li><a href=\"/person/A002068\">Carl</a></li></ul>",
      "hints": [
        "Mit xsl:attribute name=\"href\" baust du das href dynamisch.",
        "concat('/person/', @key) setzt den Pfad zusammen.",
        "<ul><xsl:for-each select=\"//tei:persName[@key]\"><li><a><xsl:attribute name=\"href\"><xsl:value-of select=\"concat('/person/', @key)\"/></xsl:attribute><xsl:value-of select=\".\"/></a></li></xsl:for-each></ul>"
      ],
      "solution": "<ul><xsl:for-each select=\"//tei:persName[@key]\"><li><a><xsl:attribute name=\"href\"><xsl:value-of select=\"concat('/person/', @key)\"/></xsl:attribute><xsl:value-of select=\".\"/></a></li></xsl:for-each></ul>",
      "explanation": "So baut die WeGA Personenlinks: aus dem @key wird eine URL zur Personen-Detailseite. Du könntest auch href=\"/person/{@key}\" als AVT schreiben — beides ist gültig.",
      "conceptTag": "attribute"
    },
    {
      "id": "w3c11",
      "world": 3,
      "worldName": "XSLT Basics",
      "title": "xsl:variable nutzen",
      "task": "Binde den Absender an eine Variable $sender und gib 'Absender: NAME' in einem <p> aus.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<p>Absender: Carl Maria von Weber</p>",
      "hints": [
        "xsl:variable name=\"x\" select=\"...\" bindet einen Wert.",
        "Auf die Variable greifst du mit $x zu.",
        "<xsl:variable name=\"sender\" select=\"//tei:correspAction[@type='sent']//tei:persName\"/><p>Absender: <xsl:value-of select=\"$sender\"/></p>"
      ],
      "solution": "<xsl:variable name=\"sender\" select=\"//tei:correspAction[@type='sent']//tei:persName\"/><p>Absender: <xsl:value-of select=\"$sender\"/></p>",
      "explanation": "xsl:variable verbessert Lesbarkeit und vermeidet Wiederholung langer XPath-Pfade. Achtung: XSLT-Variablen sind unveränderlich (kein Neuzuweisen).",
      "conceptTag": "variable"
    },
    {
      "id": "w3c12",
      "world": 3,
      "worldName": "XSLT Basics",
      "title": "xsl:element dynamisch",
      "task": "Erzeuge mit xsl:element ein <section>-Element, das den Absendernamen enthält.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<section>Carl Maria von Weber</section>",
      "hints": [
        "xsl:element name=\"...\" erzeugt ein Element, dessen Name zur Laufzeit bestimmt werden kann.",
        "Der Inhalt steht zwischen <xsl:element> und </xsl:element>.",
        "<xsl:element name=\"section\"><xsl:value-of select=\"//tei:correspAction[@type='sent']//tei:persName\"/></xsl:element>"
      ],
      "solution": "<xsl:element name=\"section\"><xsl:value-of select=\"//tei:correspAction[@type='sent']//tei:persName\"/></xsl:element>",
      "explanation": "xsl:element ist nötig, wenn der Elementname dynamisch ist (z. B. aus einem Attribut käme: name=\"{@type}\"). Bei festem Namen genügt normales Literal-Markup.",
      "conceptTag": "element"
    }
  ],
  "world4": [
    {
      "id": "w4c01",
      "world": 4,
      "worldName": "WeGA Patterns",
      "title": "del überspringen",
      "task": "Gib alle Absätze (tei:p im body) als <p> aus, aber unterdrücke den Inhalt von tei:del. Nutze apply-templates.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<div><p>Meine innig geliebte Lina! Schon wieder sind einige Tage vergangen, ohne dass ich Dir schreiben konnte. Die Proben zur Freischütz-Ouvertüre nehmen all meine Zeit in Anspruch.</p><p>Gestern sprach ich mit Friedrich Kind über das Textbuch. Er ist mit den ÄnderungenEndrungen einverstanden. Auch Herr Brühl lässt grüßen.</p><p>Die Aufforderung zum Tanz habe ich beinahe vollendet. Weber arbeitete von 1815 bis 1819 an mehreren Klavierwerken parallel.</p><p>Lebe wohl, mein Herz. Die Unterschrift ist im Original stark verblasst. Dein treuer Carl.</p></div>",
      "hints": [
        "Ein leeres Template <xsl:template match=\"tei:del\"/> unterdrückt diese Elemente.",
        "Mit xsl:apply-templates ohne select rufst du die Templates für alle Kinder auf.",
        "<xsl:template match=\"/\"><div><xsl:apply-templates select=\"//tei:body//tei:p\"/></div></xsl:template>\n<xsl:template match=\"tei:p\"><p><xsl:apply-templates/></p></xsl:template>\n<xsl:template match=\"tei:del\"/>"
      ],
      "solution": "<xsl:template match=\"/\"><div><xsl:apply-templates select=\"//tei:body//tei:p\"/></div></xsl:template>\n<xsl:template match=\"tei:p\"><p><xsl:apply-templates/></p></xsl:template>\n<xsl:template match=\"tei:del\"/>",
      "explanation": "Ein leeres Template ist das klassische Pattern, um Inhalte zu unterdrücken. Die WeGA nutzt das, um getilgten Text (tei:del) standardmäßig auszublenden. Hinweis: tei:choice zeigt hier noch beide Lesarten — das räumt Challenge 6 auf.",
      "conceptTag": "apply-templates"
    },
    {
      "id": "w4c02",
      "world": 4,
      "worldName": "WeGA Patterns",
      "title": "Push-Style statt for-each",
      "task": "Erzeuge eine <ul> mit einem <li> pro tei:persName — aber mit apply-templates statt for-each.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<ul><li>Carl Maria von Weber</li><li>Caroline Brandt</li><li>Lina</li><li>Friedrich Kind</li><li>Brühl</li><li>Carl</li></ul>",
      "hints": [
        "apply-templates select=\"...\" delegiert an ein passendes Template.",
        "Schreibe ein eigenes Template für tei:persName.",
        "<xsl:template match=\"/\"><ul><xsl:apply-templates select=\"//tei:persName\"/></ul></xsl:template>\n<xsl:template match=\"tei:persName\"><li><xsl:value-of select=\".\"/></li></xsl:template>"
      ],
      "solution": "<xsl:template match=\"/\"><ul><xsl:apply-templates select=\"//tei:persName\"/></ul></xsl:template>\n<xsl:template match=\"tei:persName\"><li><xsl:value-of select=\".\"/></li></xsl:template>",
      "explanation": "Push-style (apply-templates + match) ist der bevorzugte XSLT-Stil der WeGA: Jeder Elementtyp bekommt sein eigenes Template, der Prozessor wählt automatisch das passende. Das skaliert besser als verschachtelte for-each.",
      "conceptTag": "apply-templates"
    },
    {
      "id": "w4c03",
      "world": 4,
      "worldName": "WeGA Patterns",
      "title": "Named Template für Datum",
      "task": "Schreibe ein benanntes Template 'fmtdate', das ein übergebenes Datum in <span class=\"date\">…</span> rendert, und rufe es für das Versanddatum auf.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<div><span class=\"date\">1817-02-12</span></div>",
      "hints": [
        "xsl:template name=\"...\" definiert ein aufrufbares Template (ohne match).",
        "xsl:call-template name=\"...\" mit xsl:with-param übergibt Parameter.",
        "<xsl:template match=\"/\"><div><xsl:call-template name=\"fmtdate\"><xsl:with-param name=\"d\" select=\"//tei:correspAction[@type='sent']/tei:date/@when\"/></xsl:call-template></div></xsl:template>\n<xsl:template name=\"fmtdate\"><xsl:param name=\"d\"/><span class=\"date\"><xsl:value-of select=\"$d\"/></span></xsl:template>"
      ],
      "solution": "<xsl:template match=\"/\"><div><xsl:call-template name=\"fmtdate\"><xsl:with-param name=\"d\" select=\"//tei:correspAction[@type='sent']/tei:date/@when\"/></xsl:call-template></div></xsl:template>\n<xsl:template name=\"fmtdate\"><xsl:param name=\"d\"/><span class=\"date\"><xsl:value-of select=\"$d\"/></span></xsl:template>",
      "explanation": "Named Templates sind wie Funktionen: einmal definiert, mehrfach aufrufbar. Die WeGA bündelt so wiederkehrende Formatierungen (Datum, Seitenangaben) an einer Stelle.",
      "conceptTag": "named template"
    },
    {
      "id": "w4c04",
      "world": 4,
      "worldName": "WeGA Patterns",
      "title": "Modi: inline vs. Index",
      "task": "Rendere den ersten tei:persName zweimal: einmal im Modus 'inline' (Name in <span class=\"inline\">), einmal im Modus 'index' (@key in <span class=\"index\">).",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<div><span class=\"inline\">Carl Maria von Weber</span><span class=\"index\">A002068</span></div>",
      "hints": [
        "Mit mode=\"...\" kann derselbe Knoten je nach Kontext anders gerendert werden.",
        "apply-templates select=\"...\" mode=\"inline\" ruft nur Templates mit diesem Modus auf.",
        "<xsl:template match=\"/\"><div><xsl:apply-templates select=\"(//tei:persName)[1]\" mode=\"inline\"/><xsl:apply-templates select=\"(//tei:persName)[1]\" mode=\"index\"/></div></xsl:template>\n<xsl:template match=\"tei:persName\" mode=\"inline\"><span class=\"inline\"><xsl:value-of select=\".\"/></span></xsl:template>\n<xsl:template match=\"tei:persName\" mode=\"index\"><span class=\"index\"><xsl:value-of select=\"@key\"/></span></xsl:template>"
      ],
      "solution": "<xsl:template match=\"/\"><div><xsl:apply-templates select=\"(//tei:persName)[1]\" mode=\"inline\"/><xsl:apply-templates select=\"(//tei:persName)[1]\" mode=\"index\"/></div></xsl:template>\n<xsl:template match=\"tei:persName\" mode=\"inline\"><span class=\"inline\"><xsl:value-of select=\".\"/></span></xsl:template>\n<xsl:template match=\"tei:persName\" mode=\"index\"><span class=\"index\"><xsl:value-of select=\"@key\"/></span></xsl:template>",
      "explanation": "Modi (mode) erlauben mehrere Darstellungen desselben Elements — z. B. persName inline im Brieftext vs. als Eintrag im Personenregister. Ein zentrales WeGA-Pattern für Mehrfachausgaben.",
      "conceptTag": "mode"
    },
    {
      "id": "w4c05",
      "world": 4,
      "worldName": "WeGA Patterns",
      "title": "Priority und Spezifität",
      "task": "Rendere alle Kinder der sent-Aktion. Allgemeine Elemente als <span class=\"generic\">local-name()</span>, aber tei:persName per höher priorisiertem Template als <span class=\"person\">Name</span>.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<div><span class=\"person\">Carl Maria von Weber</span><span class=\"generic\">date</span><span class=\"generic\">placeName</span></div>",
      "hints": [
        "Bei zwei passenden Templates gewinnt das mit höherer priority.",
        "Setze priority=\"2\" auf das persName-Template.",
        "<xsl:template match=\"/\"><div><xsl:apply-templates select=\"//tei:correspAction[@type='sent']/*\"/></div></xsl:template>\n<xsl:template match=\"tei:correspAction/*\"><span class=\"generic\"><xsl:value-of select=\"local-name()\"/></span></xsl:template>\n<xsl:template match=\"tei:persName\" priority=\"2\"><span class=\"person\"><xsl:value-of select=\".\"/></span></xsl:template>"
      ],
      "solution": "<xsl:template match=\"/\"><div><xsl:apply-templates select=\"//tei:correspAction[@type='sent']/*\"/></div></xsl:template>\n<xsl:template match=\"tei:correspAction/*\"><span class=\"generic\"><xsl:value-of select=\"local-name()\"/></span></xsl:template>\n<xsl:template match=\"tei:persName\" priority=\"2\"><span class=\"person\"><xsl:value-of select=\".\"/></span></xsl:template>",
      "explanation": "Wenn mehrere Templates auf denselben Knoten passen, entscheidet die priority (höher gewinnt). Ohne explizite priority gelten Standard-Prioritäten nach Spezifität des Patterns. So überschreibt man gezielt ein allgemeines Template für einen Sonderfall.",
      "conceptTag": "priority"
    },
    {
      "id": "w4c06",
      "world": 4,
      "worldName": "WeGA Patterns",
      "title": "tei:choice rendern",
      "task": "Rendere den zweiten Absatz (//tei:p[2]) als <p>. Zeige bei tei:choice die korrigierte Lesart (tei:corr), verstecke tei:sic. Zeige persName als Text, behalte tei:add-Inhalt.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<div><p>Gestern sprach ich mit Friedrich Kind über das Textbuch. Er ist mit den Änderungen einverstanden. Auch Herr Brühl lässt grüßen.</p></div>",
      "hints": [
        "Ein Template für tei:choice rendert nur tei:corr; ein leeres Template versteckt tei:sic.",
        "Achte darauf, dass das p-Template seine Kinder per apply-templates verarbeitet.",
        "<xsl:template match=\"/\"><div><xsl:apply-templates select=\"//tei:p[2]\"/></div></xsl:template>\n<xsl:template match=\"tei:p\"><p><xsl:apply-templates/></p></xsl:template>\n<xsl:template match=\"tei:choice\"><xsl:apply-templates select=\"tei:corr\"/></xsl:template>\n<xsl:template match=\"tei:sic\"/>\n<xsl:template match=\"tei:persName\"><xsl:value-of select=\".\"/></xsl:template>\n<xsl:template match=\"tei:add\"><xsl:apply-templates/></xsl:template>"
      ],
      "solution": "<xsl:template match=\"/\"><div><xsl:apply-templates select=\"//tei:p[2]\"/></div></xsl:template>\n<xsl:template match=\"tei:p\"><p><xsl:apply-templates/></p></xsl:template>\n<xsl:template match=\"tei:choice\"><xsl:apply-templates select=\"tei:corr\"/></xsl:template>\n<xsl:template match=\"tei:sic\"/>\n<xsl:template match=\"tei:persName\"><xsl:value-of select=\".\"/></xsl:template>\n<xsl:template match=\"tei:add\"><xsl:apply-templates/></xsl:template>",
      "explanation": "tei:choice/tei:corr+tei:sic kodiert Korrektur vs. Original. Die Editionssicht zeigt die emendierte Form. Dies ist eng verwandt mit dem WeGA-Issue #438: tei:choice/tei:app-Strukturen müssen sauber inline gerendert werden, ohne ungültiges HTML zu erzeugen.",
      "conceptTag": "choice/apparatus"
    },
    {
      "id": "w4c07",
      "world": 4,
      "worldName": "WeGA Patterns",
      "title": "Rekursion: verschachtelte Liste",
      "task": "Rendere die verschachtelte tei:list als verschachtelte <ul>/<li>. Beginne bei der äußersten Liste (nested_list).",
      "type": "xslt",
      "fixture": "nested_list",
      "expectedType": "html",
      "expected": "<ul><li>Opern<ul><li>Freischütz</li><li>Euryanthe</li></ul></li><li>Klavierwerke</li></ul>",
      "hints": [
        "Ein tei:list-Template, das tei:item verarbeitet; ein tei:item-Template, das wiederum tei:list verarbeitet — das ergibt Rekursion.",
        "Starte nur bei der obersten Liste: tei:TEI/tei:text/tei:body/tei:list, sonst wird die innere doppelt gerendert.",
        "<xsl:template match=\"/\"><xsl:apply-templates select=\"tei:TEI/tei:text/tei:body/tei:list\"/></xsl:template>\n<xsl:template match=\"tei:list\"><ul><xsl:apply-templates select=\"tei:item\"/></ul></xsl:template>\n<xsl:template match=\"tei:item\"><li><xsl:value-of select=\"text()\"/><xsl:apply-templates select=\"tei:list\"/></li></xsl:template>"
      ],
      "solution": "<xsl:template match=\"/\"><xsl:apply-templates select=\"tei:TEI/tei:text/tei:body/tei:list\"/></xsl:template>\n<xsl:template match=\"tei:list\"><ul><xsl:apply-templates select=\"tei:item\"/></ul></xsl:template>\n<xsl:template match=\"tei:item\"><li><xsl:value-of select=\"text()\"/><xsl:apply-templates select=\"tei:list\"/></li></xsl:template>",
      "explanation": "Rekursion entsteht ganz natürlich aus apply-templates: list ruft item, item ruft (falls vorhanden) wieder list. Wichtig ist der Einstieg über die oberste Liste — sonst rendert das //-Muster die innere Liste doppelt (ein häufiger Anfängerfehler).",
      "conceptTag": "Rekursion"
    },
    {
      "id": "w4c08",
      "world": 4,
      "worldName": "WeGA Patterns",
      "title": "String-Manipulation in XSLT 1.0",
      "task": "Forme den @key der ersten Person um zu 'X-restY', wobei X das erste Zeichen ist, ein Bindestrich folgt, und im Rest alle '0' durch 'X' ersetzt sind. (substring, translate, concat).",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<p>A-XX2X68</p>",
      "hints": [
        "substring(s, 1, 1) gibt das erste Zeichen; substring(s, 2) den Rest.",
        "translate(s, '0', 'X') ersetzt zeichenweise.",
        "<p><xsl:value-of select=\"concat(substring(//tei:persName[1]/@key,1,1), '-', translate(substring(//tei:persName[1]/@key,2),'0','X'))\"/></p>"
      ],
      "solution": "<p><xsl:value-of select=\"concat(substring(//tei:persName[1]/@key,1,1), '-', translate(substring(//tei:persName[1]/@key,2),'0','X'))\"/></p>",
      "explanation": "XSLT 1.0 hat keine Regex und kein replace(). substring(), translate() und concat() sind die Werkzeuge für String-Verarbeitung. translate() ist eine zeichenweise Ersetzung (kein String-Replace!).",
      "conceptTag": "String-Funktionen 1.0"
    },
    {
      "id": "w4c09",
      "world": 4,
      "worldName": "WeGA Patterns",
      "title": "xsl:key für Lookup",
      "task": "Definiere einen xsl:key 'byKey' über tei:persName nach @key und gib alle persName mit key('byKey','A002078') in einer <ul> aus.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<ul><li>Caroline Brandt</li><li>Lina</li></ul>",
      "hints": [
        "xsl:key name=\"...\" match=\"...\" use=\"...\" definiert einen Index (auf oberster Ebene).",
        "key('name', wert) findet alle indizierten Knoten mit diesem Wert.",
        "<xsl:key name=\"byKey\" match=\"tei:persName\" use=\"@key\"/>\n<xsl:template match=\"/\"><ul><xsl:for-each select=\"key('byKey','A002078')\"><li><xsl:value-of select=\".\"/></li></xsl:for-each></ul></xsl:template>"
      ],
      "solution": "<xsl:key name=\"byKey\" match=\"tei:persName\" use=\"@key\"/>\n<xsl:template match=\"/\"><ul><xsl:for-each select=\"key('byKey','A002078')\"><li><xsl:value-of select=\".\"/></li></xsl:for-each></ul></xsl:template>",
      "explanation": "xsl:key baut einen Index für schnelle Lookups — unverzichtbar, wenn man in großen Dokumenten oft nach demselben Attribut sucht (z. B. alle Vorkommen einer Person über ihren @key). xsl:key steht immer auf Stylesheet-Ebene.",
      "conceptTag": "key"
    },
    {
      "id": "w4c10",
      "world": 4,
      "worldName": "WeGA Patterns",
      "title": "local-name und namespace-uri",
      "task": "Gib für die erste tei:persName 'local-name | namespace-uri' in einem <p> aus.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<p>persName | http://www.tei-c.org/ns/1.0</p>",
      "hints": [
        "local-name() gibt den Namen ohne Präfix.",
        "namespace-uri() gibt die zugehörige Namespace-URI.",
        "<p><xsl:value-of select=\"local-name(//tei:persName[1])\"/> | <xsl:value-of select=\"namespace-uri(//tei:persName[1])\"/></p>"
      ],
      "solution": "<p><xsl:value-of select=\"local-name(//tei:persName[1])\"/> | <xsl:value-of select=\"namespace-uri(//tei:persName[1])\"/></p>",
      "explanation": "local-name() und namespace-uri() sind essenziell beim Arbeiten mit Namespaces. In TEI hilft local-name() oft, Templates unabhängig vom Präfix zu schreiben.",
      "conceptTag": "Namespace-Funktionen"
    },
    {
      "id": "w4c11",
      "world": 4,
      "worldName": "WeGA Patterns",
      "title": "Output-Encoding korrekt",
      "task": "Gib den Text 'Weber & Brandt <1817>' korrekt escaped in einem <p> aus (ohne disable-output-escaping). Verwende xsl:text mit den Entities.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<p>Weber &amp; Brandt &lt;1817&gt;</p>",
      "hints": [
        "Im Stylesheet schreibst du Sonderzeichen als Entities: &amp; &lt; &gt;",
        "xsl:text gibt buchstäblichen Text aus; der Prozessor escaped korrekt für die Ausgabe.",
        "<p><xsl:text>Weber &amp; Brandt &lt;1817&gt;</xsl:text></p>"
      ],
      "solution": "<p><xsl:text>Weber &amp; Brandt &lt;1817&gt;</xsl:text></p>",
      "explanation": "Korrektes Encoding ist Pflicht: & wird zu &amp;, < zu &lt;. disable-output-escaping ist ein Anti-Pattern (Sicherheits-/Validitätsrisiko) und in der WeGA tabu. Der Prozessor escaped automatisch richtig.",
      "conceptTag": "Encoding"
    },
    {
      "id": "w4c12",
      "world": 4,
      "worldName": "WeGA Patterns",
      "title": "Integration: kompletter Brief",
      "task": "Rendere alle Absätze als <article> mit <p>. persName als Links <a href=\"/person/KEY\">, tei:rs als <em>, tei:note als <span class=\"footnote\">, tei:choice nur corr, tei:del unterdrückt, tei:add-Inhalt behalten.",
      "type": "xslt",
      "fixture": "letter_001",
      "expectedType": "html",
      "expected": "<article><p>Meine innig geliebte <a href=\"/person/A002078\">Lina</a>! Schon wieder sind einige Tage vergangen, ohne dass ich Dir schreiben konnte. Die Proben zur <em>Freischütz</em>-Ouvertüre nehmen all meine Zeit in Anspruch.</p><p>Gestern sprach ich mit <a href=\"/person/A002099\">Friedrich Kind</a> über das Textbuch. Er ist mit den Änderungen einverstanden. Auch Herr <a href=\"/person/A002101\">Brühl</a> lässt grüßen.</p><p>Die <em>Aufforderung zum Tanz</em> habe ich beinahe vollendet. <span class=\"footnote\">Weber arbeitete von 1815 bis 1819 an mehreren Klavierwerken parallel.</span></p><p>Lebe wohl, mein Herz. <span class=\"footnote\">Die Unterschrift ist im Original stark verblasst.</span> Dein treuer <a href=\"/person/A002068\">Carl</a>.</p></article>",
      "hints": [
        "Schreibe je ein Template pro Elementtyp und nutze überall apply-templates.",
        "Für persName: <a href=\"{concat('/person/', @key)}\">; für rs: <em>; für note: span.footnote; choice: nur corr; del: leeres Template.",
        "<xsl:template match=\"/\"><article><xsl:apply-templates select=\"//tei:body//tei:p\"/></article></xsl:template>\n<xsl:template match=\"tei:p\"><p><xsl:apply-templates/></p></xsl:template>\n<xsl:template match=\"tei:persName\"><a href=\"{concat('/person/', @key)}\"><xsl:value-of select=\".\"/></a></xsl:template>\n<xsl:template match=\"tei:note\"><span class=\"footnote\"><xsl:value-of select=\".\"/></span></xsl:template>\n<xsl:template match=\"tei:choice\"><xsl:value-of select=\"tei:corr\"/></xsl:template>\n<xsl:template match=\"tei:del\"/>\n<xsl:template match=\"tei:rs\"><em><xsl:value-of select=\".\"/></em></xsl:template>\n<xsl:template match=\"tei:add\"><xsl:apply-templates/></xsl:template>"
      ],
      "solution": "<xsl:template match=\"/\"><article><xsl:apply-templates select=\"//tei:body//tei:p\"/></article></xsl:template>\n<xsl:template match=\"tei:p\"><p><xsl:apply-templates/></p></xsl:template>\n<xsl:template match=\"tei:persName\"><a href=\"{concat('/person/', @key)}\"><xsl:value-of select=\".\"/></a></xsl:template>\n<xsl:template match=\"tei:note\"><span class=\"footnote\"><xsl:value-of select=\".\"/></span></xsl:template>\n<xsl:template match=\"tei:choice\"><xsl:value-of select=\"tei:corr\"/></xsl:template>\n<xsl:template match=\"tei:del\"/>\n<xsl:template match=\"tei:rs\"><em><xsl:value-of select=\".\"/></em></xsl:template>\n<xsl:template match=\"tei:add\"><xsl:apply-templates/></xsl:template>",
      "explanation": "Das ist die WeGA-Realität: ein push-style Stylesheet mit einem Template pro TEI-Element. Der Prozessor läuft rekursiv durch den Baum, jedes Element wird nach seiner Rolle gerendert (persName→Link, rs→Werktitel, note→Fußnote). Genau so ist wega-letters.xsl aufgebaut.",
      "conceptTag": "Integration"
    }
  ],
  "world5": [
    {
      "id": "w5c01",
      "world": 5,
      "worldName": "eXist-db Query",
      "title": "declare function verstehen",
      "task": "Was macht die folgende XQuery-Deklaration?\n\ndeclare function local:person-name($key as xs:string) as xs:string? {\n  let $person := doc(concat('/db/apps/WeGA-WebApp/data/persons/', $key, '.xml'))\n  return $person//tei:persName[@type='reg']/string()\n};",
      "type": "explain",
      "fixture": null,
      "conceptTag": "XQuery-Grundstruktur",
      "options": [
        "Importiert ein externes XQuery-Modul aus der Datenbank",
        "Deklariert eine wiederverwendbare Funktion, die für eine WeGA-ID das normierte Personennamen-Element liefert",
        "Erstellt eine globale Variable mit dem Namen 'person-name'",
        "Definiert einen XML-Namespace mit dem Präfix 'local'"
      ],
      "correctOption": 1,
      "hints": [
        "declare function leitet immer eine Funktionsdeklaration ein.",
        "local: ist der Namespace-Präfix für benutzerdefinierte Funktionen in XQuery.",
        "Der Körper in { } enthält let und return — das ist ein FLWOR-Ausdruck."
      ],
      "solution": "B — Deklariert eine wiederverwendbare Funktion",
      "explanation": "declare function local:name($param) { ... }; ist die XQuery-Syntax für Funktionen. local: ist der Standard-Präfix für eigene Funktionen. as xs:string? bedeutet: Rückgabetyp ist ein optionaler String (? = 0 oder 1 Wert). Der Körper lädt ein Dokument mit doc() und gibt den normalisierten Personennamen zurück.",
      "expected": null,
      "expectedType": "choice"
    },
    {
      "id": "w5c02",
      "world": 5,
      "worldName": "eXist-db Query",
      "title": "module namespace vs. import module",
      "task": "Was ist der Unterschied zwischen diesen beiden Deklarationen?\n\nmodule namespace app=\"http://xquery.weber-gesamtausgabe.de/modules/app\";\n\nimport module namespace wega-util=\"http://xquery.weber-gesamtausgabe.de/modules/wega-util\"\n  at \"wega-util.xqm\";",
      "type": "explain",
      "fixture": null,
      "conceptTag": "XQuery-Grundstruktur",
      "options": [
        "Kein Unterschied — beide importieren Module",
        "module namespace deklariert das aktuelle Modul (wer ich bin). import module namespace lädt ein externes Modul (was ich nutze).",
        "module namespace gilt nur in eXist-db, import module namespace ist Standard-XQuery",
        "module namespace ist für XML-Namespaces, import module namespace für JavaScript-Module"
      ],
      "correctOption": 1,
      "hints": [
        "module namespace steht ganz oben in Bibliotheks-Modulen (.xqm-Dateien).",
        "import module namespace braucht at '...' damit eXist-db die Datei findet.",
        "Hauptmodule (.xql) deklarieren keinen module namespace — die werden direkt aufgerufen."
      ],
      "solution": "B — module namespace deklariert das aktuelle Modul; import module namespace lädt ein fremdes",
      "explanation": "module namespace app=\"...\" ist der Header eines Bibliotheks-Moduls: Es sagt 'Ich bin das Modul mit diesem Namespace'. import module namespace wega-util=\"...\" at \"...\" lädt ein anderes Modul in den aktuellen Scope — wie 'import' in Python oder JavaScript. Die at-Klausel gibt den physischen Pfad an. Haupt-XQL-Dateien deklarieren keinen eigenen Namespace, sondern importieren nur.",
      "expected": null,
      "expectedType": "choice"
    },
    {
      "id": "w5c03",
      "world": 5,
      "worldName": "eXist-db Query",
      "title": "doc() vs. collection()",
      "task": "Wann verwendest du doc() und wann collection()?\n\ndoc('/db/data/A040001.xml')\ncollection('/db/data/letters')//tei:TEI",
      "type": "explain",
      "fixture": null,
      "conceptTag": "XQuery-Grundstruktur",
      "options": [
        "doc() ist schneller, collection() ist genauer — je nach Performancebedarf wählen",
        "doc() ist für alte eXist-Versionen, collection() für neue",
        "doc() lädt genau ein XML-Dokument anhand seines Pfades. collection() gibt alle Dokumente in einem Verzeichnis zurück — für Abfragen über viele Dokumente gleichzeitig.",
        "doc() gibt rohen XML-Text zurück, collection() gibt DOM-Knoten"
      ],
      "correctOption": 2,
      "hints": [
        "doc() braucht einen vollständigen Datei-Pfad inklusive .xml-Endung.",
        "collection() braucht nur den Ordner-Pfad, liefert alle darin enthaltenen Dokumente.",
        "In der WeGA: doc() für 'gib mir Brief A040001', collection() für 'alle Briefe von 1817'."
      ],
      "solution": "C — doc() = ein Dokument, collection() = viele Dokumente in einem Verzeichnis",
      "explanation": "doc('/db/data/A040001.xml') öffnet genau dieses eine Dokument — du kennst die ID. collection('/db/data/letters') öffnet alle XML-Dateien in diesem Verzeichnis. Kombiniert mit //tei:TEI und FLWOR kann man so die gesamte Briefdatenbank abfragen: 'alle Briefe von Absender X', 'alle Dokumente aus 1817' etc.",
      "expected": null,
      "expectedType": "choice"
    },
    {
      "id": "w5c04",
      "world": 5,
      "worldName": "eXist-db Query",
      "title": "request:get-parameter() Standardwert",
      "task": "Was passiert, wenn der URL-Parameter 'id' nicht übergeben wird?\n\nlet $id := request:get-parameter('id', '')",
      "type": "explain",
      "fixture": null,
      "conceptTag": "HTTP in eXist-db",
      "options": [
        "eXist-db wirft einen Fehler und bricht ab",
        "$id bekommt den Wert '' (leerer String) — den Standardwert (zweites Argument)",
        "$id bekommt den Wert () — eine leere Sequenz",
        "Die Funktion gibt undefined zurück"
      ],
      "correctOption": 1,
      "hints": [
        "Das zweite Argument von request:get-parameter() ist der Fallback-Wert.",
        "Bei '' (leerem String) als Fallback musst du danach prüfen: if ($id = '') then error(...) else ..."
      ],
      "solution": "B — $id = '' (der Standardwert aus dem zweiten Argument)",
      "explanation": "request:get-parameter('paramname', 'default') ist das Standard-Pattern in eXist-db. Das zweite Argument ist der Rückgabewert, wenn der Parameter fehlt. '' (leerer String) als Default ist üblich — dann prüft man nachher: if ($id = '') then response:set-status-code(400) else .... Ein anderer üblicher Fallback: () für eine leere Sequenz.",
      "expected": null,
      "expectedType": "choice"
    },
    {
      "id": "w5c05",
      "world": 5,
      "worldName": "eXist-db Query",
      "title": "HTTP-Response als JSON",
      "task": "Schreibe eine eXist-db XQuery-Funktion, die:\n1. Einen 'id'-Parameter liest (Fallback: '')\n2. Das Dokument lädt: doc('/db/data/' || $id || '.xml')\n3. Den normierten Personennamen (tei:persName[@type='reg']) holt\n4. Als JSON zurückgibt: { \"name\": \"...\" }\n\nNutze: response:set-header(), serialize(), map{}",
      "type": "write-only",
      "fixture": null,
      "conceptTag": "HTTP in eXist-db",
      "hints": [
        "Deklariere zuerst den tei-Namespace: declare namespace tei=\"http://www.tei-c.org/ns/1.0\";",
        "response:set-header('Content-Type', 'application/json') muss vor der Ausgabe kommen.",
        "serialize(map { 'name': $name }, map { 'method': 'json' }) wandelt eine XQuery-map in JSON um."
      ],
      "solution": "declare namespace tei=\"http://www.tei-c.org/ns/1.0\";\n\nlet $id := request:get-parameter('id', '')\nlet $doc := doc('/db/data/' || $id || '.xml')\nlet $name := $doc//tei:persName[@type='reg']/string()\nlet $_ := response:set-header('Content-Type', 'application/json')\nreturn serialize(\n  map { 'name': $name },\n  map { 'method': 'json' }\n)",
      "explanation": "Das ist das Grundmuster für JSON-Endpunkte in der WeGA. request:get-parameter() holt den URL-Parameter. Doc() + XPath holt den Wert. map{} baut eine XQuery-Map (= JSON-Objekt). serialize() mit method:'json' wandelt das in JSON-Text um. response:set-header() setzt den richtigen MIME-Type.",
      "expected": null,
      "expectedType": "write-only"
    },
    {
      "id": "w5c06",
      "world": 5,
      "worldName": "eXist-db Query",
      "title": "try/catch in XQuery",
      "task": "Was passiert wenn das Dokument nicht existiert?\n\ntry {\n  doc(concat('/db/data/', $id, '.xml'))//tei:persName[@type='reg']/string()\n} catch * {\n  error((), 'Dokument nicht gefunden: ' || $id)\n}",
      "type": "explain",
      "fixture": null,
      "conceptTag": "HTTP in eXist-db",
      "options": [
        "doc() gibt eine leere Sequenz zurück, der catch-Block wird nie ausgeführt",
        "doc() wirft einen Fehler → catch * fängt ALLE Fehler → error() löst einen neuen Fehler aus, den eXist-db als HTTP 500 ausliefert",
        "Der Code gibt 'Dokument nicht gefunden: ...' als normalen String zurück",
        "XQuery hat kein try/catch — dieser Code ist ungültig"
      ],
      "correctOption": 1,
      "hints": [
        "doc() wirft einen Fehler wenn die Datei nicht existiert (anders als in XPath wo es eine leere Sequenz wäre).",
        "catch * = fange alle Fehler-Codes. In XQuery 3.1 gibt es spezifischere Patterns.",
        "error() löst absichtlich einen Fehler aus — eXist-db wandelt das in einen HTTP-Fehler."
      ],
      "solution": "B — doc() wirft Fehler → catch fängt ihn → error() löst neuen Fehler aus → HTTP 500",
      "explanation": "In eXist-db wirft doc() einen err:FODC0002-Fehler wenn das Dokument nicht existiert. try/catch fängt das ab. error((), 'message') löst danach einen eigenen Fehler aus — das ist das Pattern für kontrollierte Fehlermeldungen. eXist-db liefert das als HTTP 500 Internal Server Error aus. Besser wäre response:set-status-code(404) vor error().",
      "expected": null,
      "expectedType": "choice"
    },
    {
      "id": "w5c07",
      "world": 5,
      "worldName": "eXist-db Query",
      "title": "Alle Briefe eines Absenders",
      "task": "Schreibe XQuery (kein Browser-Runner), das alle Briefe findet,\nwo Caroline Brandt (@key='A002078') Absenderin ist.\n\nNutze collection('/db/data/letters') und FLWOR.\nGib für jeden Brief die @xml:id zurück.",
      "type": "write-only",
      "fixture": null,
      "conceptTag": "TEI-Datenbankabfragen",
      "hints": [
        "collection('/db/data/letters')//tei:TEI iteriert über alle Briefe.",
        "In der sent-Aktion prüfst du: tei:correspAction[@type='sent']//tei:persName/@key = 'A002078'",
        "for $l in ... where ... return $l/@xml:id/string()"
      ],
      "solution": "declare namespace tei=\"http://www.tei-c.org/ns/1.0\";\n\nfor $l in collection('/db/data/letters')//tei:TEI\nwhere $l//tei:correspAction[@type='sent']//tei:persName/@key = 'A002078'\nreturn string($l/@xml:id)",
      "explanation": "collection() öffnet alle Dokumente im Ordner. FLWOR filtert dann mit where per Predicate auf den @key-Wert. Das ist der Standard-Pattern für 'alle Briefe von Person X' in der WeGA-Datenbank.",
      "expected": null,
      "expectedType": "write-only"
    },
    {
      "id": "w5c08",
      "world": 5,
      "worldName": "eXist-db Query",
      "title": "ft:query vs. contains()",
      "task": "Was ist der Unterschied zwischen diesen zwei Abfragen?\n\ncollection('/db/letters')//tei:body[ft:query(., 'Freischütz')]\n\ncollection('/db/letters')//tei:body[contains(string(.), 'Freischütz')]",
      "type": "explain",
      "fixture": null,
      "conceptTag": "TEI-Datenbankabfragen",
      "options": [
        "Kein praktischer Unterschied, ft:query ist nur neuere Syntax",
        "ft:query nutzt einen Lucene-Volltext-Index — extrem schnell, index-basiert. contains() prüft jeden String einzeln — langsam bei großen Sammlungen, aber kein Index nötig.",
        "ft:query ist case-sensitive, contains() ist case-insensitiv",
        "ft:query gibt Rangfolgen zurück, contains() nur true/false — aber beide sind gleich schnell"
      ],
      "correctOption": 1,
      "hints": [
        "eXist-db indiziert Volltexte mit Lucene wenn in der collection.xconf konfiguriert.",
        "Ohne Lucene-Index fällt ft:query auf einen sequentiellen Scan zurück.",
        "Bei der WeGA (tausende Briefe) ist der Unterschied Millisekunden vs. Sekunden."
      ],
      "solution": "B — ft:query nutzt den Lucene-Index (schnell), contains() scannt sequentiell (langsam)",
      "explanation": "ft:query() ist eXist-dbs Volltext-Suchanfrage über den Lucene-Index. Wenn die collection.xconf einen <text match=\"//tei:body\"/>-Index definiert, ist die Suche O(log n) — also blitzschnell auch bei tausenden Dokumenten. contains(string(.), 'X') liest jeden Knoten einzeln, ist O(n) und wird bei der WeGA-Datenmenge sehr langsam. Für Produktiv-Code immer ft:query bevorzugen.",
      "expected": null,
      "expectedType": "choice"
    },
    {
      "id": "w5c09",
      "world": 5,
      "worldName": "eXist-db Query",
      "title": "Briefe pro Jahr zählen",
      "task": "Schreibe XQuery, das zählt wie viele Briefe pro Jahr in\n'/db/data/letters' vorhanden sind. Nutze group by.\n\nGib aus: 'Jahr: Anzahl' (z.B. '1817: 42').",
      "type": "write-only",
      "fixture": null,
      "conceptTag": "TEI-Datenbankabfragen",
      "hints": [
        "Das Jahr steht in @when des sent-Datums: substring(@when, 1, 4)",
        "group by $year fasst alle Briefe desselben Jahres zusammen.",
        "Nach group by: count($l) zählt die Gruppe. order by $year für chronologische Ausgabe."
      ],
      "solution": "declare namespace tei=\"http://www.tei-c.org/ns/1.0\";\n\nfor $l in collection('/db/data/letters')//tei:TEI\nlet $year := substring($l//tei:correspAction[@type='sent']/tei:date/@when, 1, 4)\nwhere $year != ''\ngroup by $year\norder by $year ascending\nreturn concat($year, ': ', count($l))",
      "explanation": "group by ist eine XQuery-3.0-Erweiterung: alle Iterationen mit demselben $year werden zu einer Gruppe zusammengefasst. Danach ist $l eine Sequenz aller Briefe dieses Jahres, count($l) zählt sie. WeGA-Einsatz: Chronologie-Übersichten, Statistik-Endpunkte.",
      "expected": null,
      "expectedType": "write-only"
    },
    {
      "id": "w5c10",
      "world": 5,
      "worldName": "eXist-db Query",
      "title": "Namespace-Deklaration in XQuery",
      "task": "Warum muss am Anfang jedes XQuery-Moduls, das TEI-Daten abfragt, diese Zeile stehen?\n\ndeclare namespace tei=\"http://www.tei-c.org/ns/1.0\";",
      "type": "explain",
      "fixture": null,
      "conceptTag": "TEI-Datenbankabfragen",
      "options": [
        "Damit eXist-db die TEI-Schema-Datei nachladen kann",
        "XQuery bindet Namespace-Präfixe nicht automatisch aus den Dokumenten. Ohne die Deklaration findet //tei:persName nichts — der Präfix 'tei' ist nicht definiert.",
        "Das ist nur eine Konvention der WeGA — technisch optional",
        "Damit die Ausgabe automatisch im TEI-Namespace serialisiert wird"
      ],
      "correctOption": 1,
      "hints": [
        "Teste selbst: schreibe //persName ohne Namespace-Deklaration — eXist-db findet nichts.",
        "Das Dokument hat xmlns=\"http://www.tei-c.org/ns/1.0\" — das ist der Default-Namespace.",
        "XQuery-Ausdrücke nutzen per Default KEINEN Namespace — auch nicht den aus dem Dokument."
      ],
      "solution": "B — XQuery kennt Namespace-Präfixe nicht automatisch aus den Dokumenten",
      "explanation": "TEI-Dokumente haben xmlns=\"http://www.tei-c.org/ns/1.0\" — das bedeutet alle Elemente gehören zu diesem Namespace. XQuery-Abfragen müssen Namespaces explizit binden. Ohne declare namespace tei=... würde //tei:persName einen Fehler werfen (unbekannter Präfix) oder nichts finden. Das ist dasselbe Problem wie im Browser: ohne Namespace-Resolver findet FontoxPath ohne tei:-Präfix ebenfalls nichts.",
      "expected": null,
      "expectedType": "choice"
    },
    {
      "id": "w5c11",
      "world": 5,
      "worldName": "eXist-db Query",
      "title": "WeGA API-Endpunkt erweitern",
      "task": "Erweitere diese Funktion um den Absender-Namen:\n\ndeclare function api:document-meta($id as xs:string) as map(*) {\n  let $doc := doc('/db/apps/WeGA-data/' || $id || '.xml')\n  let $title := $doc//tei:title[@level='a']/string()\n  let $date := $doc//tei:correspAction[@type='sent']/tei:date/@when/string()\n  return map {\n    'id': $id,\n    'title': $title,\n    'date': $date\n  }\n};\n\nFüge einen 'sender'-Schlüssel hinzu.",
      "type": "write-only",
      "fixture": null,
      "conceptTag": "WeGA-Praxis",
      "hints": [
        "Der Absender steht in //tei:correspAction[@type='sent']//tei:persName/string().",
        "let $sender := ... dann 'sender': $sender in der map{}.",
        "map{} ist ein XQuery-3.1-Konstrukt: map { 'key': $value, ... }"
      ],
      "solution": "declare namespace tei=\"http://www.tei-c.org/ns/1.0\";\n\ndeclare function api:document-meta($id as xs:string) as map(*) {\n  let $doc := doc('/db/apps/WeGA-data/' || $id || '.xml')\n  let $title := $doc//tei:title[@level='a']/string()\n  let $date := $doc//tei:correspAction[@type='sent']/tei:date/@when/string()\n  let $sender := $doc//tei:correspAction[@type='sent']//tei:persName/string()\n  return map {\n    'id': $id,\n    'title': $title,\n    'date': $date,\n    'sender': $sender\n  }\n};",
      "explanation": "map{} ist das XQuery-3.1-Konstrukt für assoziative Arrays (= JSON-Objekte). Man kann beliebig viele Schlüssel-Wert-Paare hinzufügen. $sender enthält den String-Inhalt des ersten Absender-persName. Bei mehreren Absendern wäre array{ for $p in ... return string($p) } das richtige Konstrukt für ein JSON-Array.",
      "expected": null,
      "expectedType": "write-only"
    },
    {
      "id": "w5c12",
      "world": 5,
      "worldName": "eXist-db Query",
      "title": "Komplettes XQL-Modul schreiben",
      "task": "Schreibe ein vollständiges XQuery-Bibliotheks-Modul (.xqm) mit:\n\n1. Namespace-Deklaration: module namespace local=\"http://wega-learn.example/local\"\n2. TEI-Namespace binden\n3. Helper-Funktion: local:format-name($persName as element()) as xs:string\n   → gibt '@type=reg Variante oder text() zurück'\n4. Haupt-Funktion: local:letter-summary($id as xs:string) as map(*)\n   → lädt Dokument, extrahiert Datum und Sender, gibt map{} zurück",
      "type": "write-only",
      "fixture": null,
      "conceptTag": "WeGA-Praxis",
      "hints": [
        "module namespace local=\"...\" steht ganz oben (kein main-Body, nur Funktionen).",
        "declare namespace tei=\"http://www.tei-c.org/ns/1.0\"; kommt danach.",
        "local:format-name: if ($persName[@type='reg']) then string($persName[@type='reg']) else string($persName[1])"
      ],
      "solution": "module namespace local=\"http://wega-learn.example/local\";\ndeclare namespace tei=\"http://www.tei-c.org/ns/1.0\";\n\n(:~\n : Gibt den normierten Namen einer tei:persName-Gruppe zurück.\n : @param $persName das persName-Element\n : @return normierter Namens-String\n :)\ndeclare function local:format-name($persName as element()) as xs:string {\n  if ($persName[@type='reg'])\n  then string($persName[@type='reg'])\n  else string($persName[1])\n};\n\n(:~\n : Gibt eine Zusammenfassung eines Briefes als map zurück.\n : @param $id die WeGA-ID des Briefes (z.B. A040001)\n : @return map mit id, date, sender\n :)\ndeclare function local:letter-summary($id as xs:string) as map(*) {\n  let $doc := doc('/db/apps/WeGA-data/' || $id || '.xml')\n  let $date := $doc//tei:correspAction[@type='sent']/tei:date/@when/string()\n  let $sender := $doc//tei:correspAction[@type='sent']//tei:persName[1]\n  return map {\n    'id': $id,\n    'date': $date,\n    'sender': local:format-name($sender)\n  }\n};",
      "explanation": "Ein Bibliotheks-Modul beginnt mit module namespace — es hat keinen ausführbaren Hauptkörper, nur Funktionsdeklarationen. XDoc-Kommentare (:~ ... :) dokumentieren die API. local:format-name zeigt das WeGA-Pattern: normierte Darstellung ([@type='reg']) bevorzugen, Fallback auf ersten Wert. local:letter-summary kombiniert doc(), XPath-Navigation und map{} — das Grundmuster für alle WeGA-API-Endpunkte.",
      "expected": null,
      "expectedType": "write-only"
    }
  ]
};
window.CONCEPTS = {
  "1:Grundnavigation": {
    "title": "Grundnavigation",
    "icon": "🧭",
    "lines": [
      "XPath denkt in Bäumen. Zwei Operatoren zum Navigieren:",
      "",
      "  //tei:persName   → sucht rekursiv überall im Baum",
      "  /tei:TEI/tei:... → geht Schritt für Schritt vom Wurzel",
      "",
      "tei: muss IMMER dabei stehen. TEI hat einen XML-Namespace",
      "— ohne Präfix findet XPath in Namespace-Dokumenten nichts.",
      "",
      "string() vs text():",
      "  string(el)   → kompletter Textinhalt inkl. Kinder",
      "  el/text()    → nur direkte Textknoten",
      "",
      "Beispiel:",
      "  //tei:persName/string()  →  [\"Weber\", \"Brandt\"]"
    ]
  },
  "1:Predicates": {
    "title": "Predicates",
    "icon": "🔍",
    "lines": [
      "Predicates [ ] filtern eine Knotenmenge nach Bedingungen.",
      "",
      "  [@attr]           → Attribut existiert",
      "  [@attr='Wert']    → Attribut hat genau diesen Wert",
      "  [1]               → erstes Element (1-basiert!)",
      "  [last()]          → letztes Element",
      "",
      "Wichtig: Reihenfolge der Klammerung:",
      "  //tei:p[1]       → jedes erste p im jeweiligen Elternteil",
      "  (//tei:p)[1]     → das erste p von allen — fast immer das Gewollte",
      "",
      "Beispiel:",
      "  //tei:note[@type='commentary']  →  Kommentar-Notizen"
    ]
  },
  "1:Achsen und Funktionen": {
    "title": "Achsen und Funktionen",
    "icon": "⚙️",
    "lines": [
      "Achsen navigieren relativ zum Kontextknoten:",
      "",
      "  following-sibling::*   → alle Geschwister danach",
      "  ancestor::tei:div      → Vorfahren vom Typ tei:div",
      "  descendant::*          → alle Nachfahren",
      "",
      "Wichtige Funktionen:",
      "  count(//tei:p)                 → Anzahl",
      "  normalize-space((//tei:p)[1])  → Whitespace normieren",
      "  distinct-values(//tei:note/@type) → Duplikate entfernen",
      "  local-name(node)               → Name ohne Namespace-Präfix",
      "",
      "Achtung: normalize-space() erwartet genau einen Wert.",
      "Schreibe (//tei:persName)[1], nicht //tei:persName[1]."
    ]
  },
  "2:for/return": {
    "title": "for / return",
    "icon": "🔁",
    "lines": [
      "FLWOR = for · let · where · order by · return",
      "",
      "for iteriert — wie eine Schleife:",
      "  for $p in //tei:persName",
      "  return string($p)",
      "",
      "Jede Iteration produziert einen Wert.",
      "Das Ergebnis ist eine Sequenz aller Rückgabewerte.",
      "",
      "Auch ein einzelner Funktionsaufruf ist gültiges XQuery:",
      "  distinct-values(//tei:note/@type)"
    ]
  },
  "2:let": {
    "title": "let und where",
    "icon": "📌",
    "lines": [
      "let bindet einen Wert einmal — keine Iteration:",
      "  let $sender := //tei:correspAction[@type='sent']//tei:persName[1]",
      "  return string($sender)",
      "",
      "where filtert die aktuelle Iteration:",
      "  for $n in //tei:note",
      "  where $n/@type = 'commentary'",
      "  return string($n)",
      "",
      "Unterschied: for iteriert, let berechnet, where filtert.",
      "let kann auch innerhalb von for stehen (pro Iteration)."
    ]
  },
  "2:where": {
    "title": "where",
    "icon": "🔎",
    "lines": [
      "where filtert — wie ein Predicate, aber lesbarer bei",
      "komplexen Bedingungen:",
      "",
      "  for $p in //tei:p",
      "  let $wc := count(tokenize(normalize-space($p), ' '))",
      "  where $wc > 10",
      "  return concat($p/@xml:id, ': ', $wc)",
      "",
      "Reihenfolge der Klauseln ist fest: for → let → where → order by → return",
      "Aber mehrere for und let können abwechseln."
    ]
  },
  "2:order by": {
    "title": "order by + Aggregation",
    "icon": "📊",
    "lines": [
      "order by sortiert die Ergebnissequenz vor dem return:",
      "  for $l in //tei:letter",
      "  order by $l/tei:correspAction[@type='sent']/tei:date/@when",
      "  return ...",
      "",
      "Aggregation ohne for — einfach die Funktion direkt:",
      "  count(//tei:persName)",
      "  distinct-values(//tei:note/@type)",
      "",
      "Kombiniert: distinct dedup, dann sortiert for:",
      "  let $all := distinct-values(//tei:persName/string())",
      "  for $p in $all order by $p return $p"
    ]
  },
  "2:verschachteltes for": {
    "title": "Verschachteltes for",
    "icon": "🔀",
    "lines": [
      "Mehrere for-Klauseln erzeugen Kombinationen:",
      "  for $l in //tei:letter",
      "  for $s in $l/tei:correspAction[@type='sent']/tei:persName",
      "  return concat(string($s), ' → ', ...)",
      "",
      "Das innere for navigiert relativ zu $l — kein kartesisches",
      "Produkt mit anderen Briefen, da $l den Kontext einschränkt.",
      "",
      "Tipp: let und for können sich abwechseln — schreibe",
      "den flüssigsten Ausdruck für den Leser."
    ]
  },
  "2:for/let/where": {
    "title": "for / let / where kombiniert",
    "icon": "🧩",
    "lines": [
      "Alle FLWOR-Klauseln zusammen:",
      "",
      "  for $p in //tei:body//tei:p",
      "  let $wc := count(tokenize(normalize-space($p), ' '))",
      "  where $wc > 10",
      "  return concat($p/@xml:id, ': ', $wc)",
      "",
      "for iteriert · let berechnet pro Iteration · where filtert",
      "· return formatiert das Ergebnis.",
      "",
      "tokenize(string, trennzeichen) zerlegt Text → Sequenz.",
      "count() zählt die Teilstücke → Wortzahl."
    ]
  },
  "2:Aggregation": {
    "title": "Aggregation",
    "icon": "📈",
    "lines": [
      "Aggregatfunktionen arbeiten auf ganzen Sequenzen:",
      "",
      "  count($seq)           → Anzahl der Items",
      "  sum($seq)             → Summe numerischer Werte",
      "  distinct-values($seq) → Duplikate entfernen",
      "  string-join($seq, ', ') → zu einem String zusammenfügen",
      "",
      "let $ps := //tei:persName   ← bindet alle Knoten",
      "return concat('Anzahl: ', count($ps))   ← gibt z.B. 'Anzahl: 6'"
    ]
  },
  "3:value-of": {
    "title": "xsl:value-of",
    "icon": "📝",
    "lines": [
      "xsl:value-of gibt IMMER einen String aus — nie ein Element.",
      "",
      "  <p><xsl:value-of select=\"//tei:persName[1]\"/></p>",
      "",
      "Attribute Value Template (AVT) in Literalattributen:",
      "  <time datetime=\"{//tei:date/@when}\">",
      "Alles in { } wird als XPath ausgewertet.",
      "",
      "xsl:value-of nimmt den ersten Knoten bei einer Sequenz.",
      "Für alle Knoten: xsl:for-each oder xsl:apply-templates."
    ]
  },
  "3:Attribute Value Template": {
    "title": "Attribute Value Template",
    "icon": "🏷️",
    "lines": [
      "Attribute Value Template (AVT): { } in Attributen:",
      "",
      "  <time datetime=\"{//tei:date/@when}\">",
      "  <a class=\"{$class}\">",
      "",
      "Nur in Literal-Attributen erlaubt, nicht in xsl:-Attributen.",
      "Alternativ: xsl:attribute",
      "  <a><xsl:attribute name=\"href\">...",
      "",
      "xsl:attribute muss VOR Textinhalt des Elements stehen,",
      "sonst ignoriert der XSLT-Prozessor es."
    ]
  },
  "3:for-each": {
    "title": "xsl:for-each",
    "icon": "🔁",
    "lines": [
      "xsl:for-each ist die explizite Schleife (pull-style):",
      "",
      "  <ul>",
      "    <xsl:for-each select=\"//tei:persName\">",
      "      <li><xsl:value-of select=\".\"/></li>",
      "    </xsl:for-each>",
      "  </ul>",
      "",
      "Innerhalb wechselt der Kontextknoten zu jedem Element.",
      ". = aktueller Knoten  ·  @ = Attribute am aktuellen Knoten",
      "",
      "xsl:sort (direkt nach dem öffnenden for-each):",
      "  <xsl:sort select=\".\" order=\"ascending\"/>"
    ]
  },
  "3:sort": {
    "title": "xsl:sort",
    "icon": "⬆️",
    "lines": [
      "xsl:sort steht als ERSTES Kind in xsl:for-each:",
      "",
      "  <xsl:for-each select=\"//tei:persName\">",
      "    <xsl:sort select=\".\"/>",
      "    <li>...</li>",
      "  </xsl:for-each>",
      "",
      "Standard: aufsteigend alphabetisch.",
      "  order=\"descending\"  → umgekehrt",
      "  data-type=\"number\"  → numerisch sortieren",
      "",
      "Bei apply-templates:",
      "  <xsl:apply-templates select=\"...\"><xsl:sort .../></xsl:apply-templates>"
    ]
  },
  "3:if": {
    "title": "xsl:if und xsl:choose",
    "icon": "❓",
    "lines": [
      "xsl:if — einfaches 'nur wenn':",
      "  <xsl:if test=\"@key\">..ausgabe..</xsl:if>",
      "",
      "Kein else! Für if/else → xsl:choose:",
      "  <xsl:choose>",
      "    <xsl:when test=\"@type='commentary'\">…</xsl:when>",
      "    <xsl:when test=\"@type='textConst'\">…</xsl:when>",
      "    <xsl:otherwise>…</xsl:otherwise>",
      "  </xsl:choose>",
      "",
      "xsl:if und xsl:choose stehen INNERHALB eines Templates."
    ]
  },
  "3:choose": {
    "title": "xsl:choose",
    "icon": "🔀",
    "lines": [
      "xsl:choose ist wie switch/case:",
      "",
      "  <xsl:choose>",
      "    <xsl:when test=\"Bedingung A\">Ausgabe A</xsl:when>",
      "    <xsl:when test=\"Bedingung B\">Ausgabe B</xsl:when>",
      "    <xsl:otherwise>Standardausgabe</xsl:otherwise>",
      "  </xsl:choose>",
      "",
      "Sehr nützlich, um CSS-Klassen oder Tag-Namen",
      "dynamisch zu wählen — z. B. je nach @type."
    ]
  },
  "3:attribute": {
    "title": "xsl:attribute und xsl:element",
    "icon": "🏗️",
    "lines": [
      "xsl:attribute setzt ein Attribut dynamisch:",
      "  <a><xsl:attribute name=\"href\">",
      "    <xsl:value-of select=\"concat('/p/', @key)\"/>",
      "  </xsl:attribute>Link</a>",
      "",
      "Regel: xsl:attribute muss vor Textinhalt stehen!",
      "",
      "xsl:element erzeugt ein Element mit dynamischem Namen:",
      "  <xsl:element name=\"{@type}\">Inhalt</xsl:element>",
      "",
      "Beide sind nötig, wenn Name zur Laufzeit bestimmt wird."
    ]
  },
  "3:variable": {
    "title": "xsl:variable",
    "icon": "📦",
    "lines": [
      "xsl:variable benennt einen Wert für späteren Zugriff:",
      "",
      "  <xsl:variable name=\"sender\"",
      "    select=\"//tei:correspAction[@type='sent']//tei:persName\"/>",
      "  <p>Absender: <xsl:value-of select=\"$sender\"/></p>",
      "",
      "Wichtig: Variablen sind unveränderlich in XSLT!",
      "Kein i++ wie in Programmiersprachen.",
      "",
      "Scope: lokal innerhalb des Template-Elements,",
      "oder global (oberste Ebene) für alle Templates."
    ]
  },
  "3:element": {
    "title": "xsl:element",
    "icon": "🧱",
    "lines": [
      "xsl:element erzeugt ein Element dessen Name aus dem",
      "Dokument kommt (dynamisch):",
      "",
      "  <xsl:element name=\"section\">Inhalt</xsl:element>",
      "  <xsl:element name=\"{@elementType}\">…</xsl:element>",
      "",
      "Bei festem Namen ist Literal-Markup kürzer:",
      "  <section>Inhalt</section>",
      "",
      "xsl:element ist nötig wenn der Name per @-Attribut",
      "oder Variable erst zur Laufzeit bekannt ist."
    ]
  },
  "4:apply-templates": {
    "title": "apply-templates (push-style)",
    "icon": "🚀",
    "lines": [
      "apply-templates delegiert an das passende Template:",
      "",
      "  <xsl:template match=\"/\">",
      "    <ul><xsl:apply-templates select=\"//tei:persName\"/></ul>",
      "  </xsl:template>",
      "  <xsl:template match=\"tei:persName\">",
      "    <li><xsl:value-of select=\".\"/></li>",
      "  </xsl:template>",
      "",
      "Ein leeres Template unterdrückt Elemente:",
      "  <xsl:template match=\"tei:del\"/>",
      "",
      "WeGA nutzt fast immer push-style — ein Template pro Element."
    ]
  },
  "4:named template": {
    "title": "Named Templates + Mode",
    "icon": "🎭",
    "lines": [
      "Named Template = Funktion (ohne match, nur mit name):",
      "  <xsl:template name=\"fmtdate\">",
      "    <xsl:param name=\"d\"/>",
      "    <span class=\"date\"><xsl:value-of select=\"$d\"/></span>",
      "  </xsl:template>",
      "",
      "Aufruf: <xsl:call-template name=\"fmtdate\">",
      "         <xsl:with-param name=\"d\" select=\"@when\"/>",
      "        </xsl:call-template>",
      "",
      "Mode = verschiedene Renderings desselben Elements:",
      "  <xsl:apply-templates select=\".\" mode=\"inline\"/>",
      "  <xsl:template match=\"tei:persName\" mode=\"inline\">…"
    ]
  },
  "4:mode": {
    "title": "Mode",
    "icon": "🔄",
    "lines": [
      "Ein Element kann in verschiedenen Modi unterschiedlich",
      "gerendert werden — ohne den XML-Baum zu verändern:",
      "",
      "  <xsl:apply-templates select=\"tei:persName\" mode=\"inline\"/>",
      "  <xsl:apply-templates select=\"tei:persName\" mode=\"index\"/>",
      "",
      "  <xsl:template match=\"tei:persName\" mode=\"inline\">",
      "    <span class=\"name\"><xsl:value-of select=\".\"/></span>",
      "  </xsl:template>",
      "  <xsl:template match=\"tei:persName\" mode=\"index\">",
      "    <xsl:value-of select=\"@key\"/>",
      "  </xsl:template>",
      "",
      "WeGA-Anwendung: persName im Brief vs. im Register."
    ]
  },
  "4:priority": {
    "title": "Priority und Spezifität",
    "icon": "🏆",
    "lines": [
      "Wenn mehrere Templates auf denselben Knoten passen,",
      "gewinnt das mit der höchsten priority.",
      "",
      "Standard-Prioritäten (ohne explizite Angabe):",
      "  *  oder node()   → 0.5 (sehr allgemein)",
      "  tei:persName     → 0   (Elementname)",
      "  tei:note[@type]  → 0.5 (mit Predicate)",
      "",
      "Explizit: <xsl:template match=\"tei:persName\" priority=\"2\">",
      "",
      "Konflikt ohne priority → Fehler oder willkürlich.",
      "Besser: immer explizit setzen wenn Templates konkurrieren."
    ]
  },
  "4:choice/apparatus": {
    "title": "tei:choice und Apparatus",
    "icon": "📚",
    "lines": [
      "tei:choice gruppiert alternative Lesarten:",
      "  <choice>",
      "    <corr>Änderungen</corr>",
      "    <sic>Endrungen</sic>",
      "  </choice>",
      "",
      "XSLT-Lösung: nur die gewünschte Lesart rendern:",
      "  <xsl:template match=\"tei:choice\">",
      "    <xsl:apply-templates select=\"tei:corr\"/>",
      "  </xsl:template>",
      "  <xsl:template match=\"tei:sic\"/>",
      "",
      "WeGA-Issue #438: tei:app hat ähnliche Struktur.",
      "Falsch gehandhabt → ungültiges HTML (block in inline)."
    ]
  },
  "4:Rekursion": {
    "title": "Rekursion in XSLT",
    "icon": "🌀",
    "lines": [
      "Rekursion entsteht natürlich durch apply-templates:",
      "",
      "  <xsl:template match=\"tei:list\">",
      "    <ul><xsl:apply-templates select=\"tei:item\"/></ul>",
      "  </xsl:template>",
      "  <xsl:template match=\"tei:item\">",
      "    <li>",
      "      <xsl:value-of select=\"text()\"/>",
      "      <xsl:apply-templates select=\"tei:list\"/>",
      "    </li>",
      "  </xsl:template>",
      "",
      "Achtung: Einstieg über die OBERSTE Liste wählen,",
      "sonst rendert //tei:list die inneren doppelt."
    ]
  },
  "4:String-Funktionen 1.0": {
    "title": "String-Manipulation in XSLT 1.0",
    "icon": "🔤",
    "lines": [
      "XSLT 1.0 hat kein replace() und keine Regex.",
      "Verfügbare Funktionen:",
      "",
      "  substring(s, start, len)   → Teilstring",
      "  substring-before(s, trenn) → alles vor dem Trenner",
      "  substring-after(s, trenn)  → alles danach",
      "  translate(s, 'abc', 'XYZ') → zeichenweise ersetzen",
      "  concat(s1, s2, ...)        → zusammenfügen",
      "  string-length(s)           → Länge",
      "",
      "Achtung: translate() ist kein String-Replace!",
      "Es ersetzt jedes Zeichen einzeln: '0'→'X', '1'→'Y' etc."
    ]
  },
  "4:key": {
    "title": "xsl:key für Lookup",
    "icon": "🗝️",
    "lines": [
      "xsl:key baut einen Index für schnelle Lookups:",
      "",
      "  <xsl:key name=\"byKey\" match=\"tei:persName\" use=\"@key\"/>",
      "",
      "Abruf mit der key()-Funktion:",
      "  key('byKey', 'A002078')   → alle persName mit @key='A002078'",
      "",
      "xsl:key steht auf Stylesheet-Ebene (Top-Level).",
      "",
      "WeGA-Anwendung: alle Vorkommen einer Person finden,",
      "ohne jedes Mal //tei:persName[@key='X'] zu schreiben."
    ]
  },
  "4:Namespace-Funktionen": {
    "title": "Namespace-Funktionen",
    "icon": "🏷️",
    "lines": [
      "local-name() und namespace-uri() helfen bei Namespaces:",
      "",
      "  local-name(//tei:persName[1])   → 'persName'",
      "  namespace-uri(//tei:persName[1]) → 'http://www.tei-c.org/ns/1.0'",
      "",
      "Nützlich, wenn du Templates schreiben willst die für",
      "beliebige TEI-Elemente gelten (unabhängig vom Präfix).",
      "",
      "In XPath 3.1: auch Q{ns}local-name Schreibweise.",
      "In XSLT 1.0: nur über prefix-Deklaration im Stylesheet."
    ]
  },
  "4:Encoding": {
    "title": "Output-Encoding",
    "icon": "🔐",
    "lines": [
      "XSLT schreibt automatisch korrektes HTML-Encoding:",
      "",
      "  & → &amp;   < → &lt;   > → &gt;",
      "",
      "Im Stylesheet selbst schreibst du Entities:",
      "  <xsl:text>Weber &amp; Brandt</xsl:text>",
      "",
      "disable-output-escaping=\"yes\" ist ein Anti-Pattern!",
      "Es umgeht das Encoding — Sicherheitsrisiko und",
      "kann zu ungültigem HTML führen. WeGA-Tabu.",
      "",
      "xsl:text gibt literalen Text aus (ohne Extra-Whitespace)."
    ]
  },
  "4:Integration": {
    "title": "Integration: kompletter Brief",
    "icon": "📄",
    "lines": [
      "Ein WeGA-Brief-Stylesheet besteht aus Templates",
      "für jeden Elementtyp — push-style:",
      "",
      "  tei:p      → <p>",
      "  tei:persName → <a href=\"/person/{@key}\">",
      "  tei:note   → <span class=\"footnote\">",
      "  tei:choice → nur tei:corr ausgeben",
      "  tei:del    → leeres Template (unterdrücken)",
      "  tei:rs     → <em>",
      "",
      "Der Prozessor traversiert den Baum und wählt",
      "automatisch das richtige Template. So funktioniert",
      "wega-letters.xsl in der echten WeGA."
    ]
  },
  "5:XQuery-Grundstruktur": {
    "title": "XQuery-Grundstruktur",
    "icon": "📦",
    "lines": [
      "XQuery erweitert XPath um Funktionen, Module und Typen.",
      "",
      "Funktionsdeklaration:",
      "  declare function local:name($param as Typ) as Typ {",
      "    (: Funktionskörper :)",
      "  };",
      "",
      "Modul-Header (für Bibliotheks-Module):",
      "  module namespace app=\"http://...\";",
      "",
      "Importieren:",
      "  import module namespace util=\"http://...\"",
      "    at \"util.xqm\";",
      "",
      "doc() = ein Dokument · collection() = viele Dokumente"
    ]
  },
  "5:HTTP in eXist-db": {
    "title": "HTTP in eXist-db",
    "icon": "🌐",
    "lines": [
      "eXist-db kann direkt HTTP-Requests beantworten.",
      "XQL-Dateien (.xql) sind Server-Endpunkte.",
      "",
      "Parameter lesen:",
      "  let $id := request:get-parameter('id', '')",
      "  (zweites Argument = Standardwert wenn fehlt)",
      "",
      "Response senden:",
      "  let $_ := response:set-header('Content-Type', 'application/json')",
      "  return serialize($result, map { 'method': 'json' })",
      "",
      "request: und response: sind eXist-db-Module.",
      "Nicht im Browser ausführbar — nur auf dem eXist-Server."
    ]
  },
  "5:TEI-Datenbankabfragen": {
    "title": "TEI-Datenbankabfragen",
    "icon": "🗃️",
    "lines": [
      "doc() vs collection():",
      "",
      "  doc('/db/data/A040001.xml')          → ein Dokument",
      "  collection('/db/data/letters')       → alle XML-Dateien",
      "    //tei:TEI                            → daraus alle TEI-Wurzeln",
      "",
      "Kombiniert mit FLWOR:",
      "  for $l in collection('/db/data/letters')//tei:TEI",
      "  let $date := $l//tei:date[@when]/@when",
      "  order by $date ascending",
      "  return $l",
      "",
      "ft:query() für Volltext: nutzt Lucene-Index,",
      "viel schneller als contains(string(.), 'text')."
    ]
  },
  "5:WeGA-Praxis": {
    "title": "WeGA-Praxis",
    "icon": "🏛️",
    "lines": [
      "WeGA-Module folgen einer festen Konvention:",
      "",
      "1. Namespace deklarieren:",
      "   module namespace app=\"http://...weber-gesamtausgabe.de/...\"",
      "",
      "2. Externe Module importieren:",
      "   import module namespace wega-util=\"...\" at \"...\";",
      "",
      "3. Funktionen mit XDoc-Kommentaren:",
      "   (:~ @param $id die WeGA-ID @return map :)",
      "   declare function app:get($id as xs:string) {",
      "     ...",
      "   };",
      "",
      "4. map{} für JSON-ähnliche Rückgabe:",
      "   map { 'id': $id, 'title': $title }"
    ]
  }
};
